
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  ADMIN: 'ADMIN',
  CALL_CENTER: 'CALL_CENTER',
  FLORIST: 'FLORIST'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const OrderType = {
  PICKUP: 'PICKUP',
  DELIVERY: 'DELIVERY'
} as const

export type OrderType = (typeof OrderType)[keyof typeof OrderType]


export const OrderStatus = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  READY: 'READY',
  PICKUP: 'PICKUP',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  COMPLETED: 'COMPLETED'
} as const

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus]


export const UnitType = {
  STEM: 'STEM',
  BUNCH: 'BUNCH',
  BOX: 'BOX'
} as const

export type UnitType = (typeof UnitType)[keyof typeof UnitType]
