
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Flower` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Flower
 * 
 */
export type FlowerModel = runtime.Types.Result.DefaultSelection<Prisma.$FlowerPayload>

export type AggregateFlower = {
  _count: FlowerCountAggregateOutputType | null
  _avg: FlowerAvgAggregateOutputType | null
  _sum: FlowerSumAggregateOutputType | null
  _min: FlowerMinAggregateOutputType | null
  _max: FlowerMaxAggregateOutputType | null
}

export type FlowerAvgAggregateOutputType = {
  stockQuantity: number | null
  lowStockLevel: number | null
}

export type FlowerSumAggregateOutputType = {
  stockQuantity: number | null
  lowStockLevel: number | null
}

export type FlowerMinAggregateOutputType = {
  id: string | null
  name: string | null
  unitType: $Enums.UnitType | null
  stockQuantity: number | null
  lowStockLevel: number | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FlowerMaxAggregateOutputType = {
  id: string | null
  name: string | null
  unitType: $Enums.UnitType | null
  stockQuantity: number | null
  lowStockLevel: number | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FlowerCountAggregateOutputType = {
  id: number
  name: number
  unitType: number
  stockQuantity: number
  lowStockLevel: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type FlowerAvgAggregateInputType = {
  stockQuantity?: true
  lowStockLevel?: true
}

export type FlowerSumAggregateInputType = {
  stockQuantity?: true
  lowStockLevel?: true
}

export type FlowerMinAggregateInputType = {
  id?: true
  name?: true
  unitType?: true
  stockQuantity?: true
  lowStockLevel?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type FlowerMaxAggregateInputType = {
  id?: true
  name?: true
  unitType?: true
  stockQuantity?: true
  lowStockLevel?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type FlowerCountAggregateInputType = {
  id?: true
  name?: true
  unitType?: true
  stockQuantity?: true
  lowStockLevel?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type FlowerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Flower to aggregate.
   */
  where?: Prisma.FlowerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Flowers to fetch.
   */
  orderBy?: Prisma.FlowerOrderByWithRelationInput | Prisma.FlowerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FlowerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Flowers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Flowers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Flowers
  **/
  _count?: true | FlowerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FlowerAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FlowerSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FlowerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FlowerMaxAggregateInputType
}

export type GetFlowerAggregateType<T extends FlowerAggregateArgs> = {
      [P in keyof T & keyof AggregateFlower]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFlower[P]>
    : Prisma.GetScalarType<T[P], AggregateFlower[P]>
}




export type FlowerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FlowerWhereInput
  orderBy?: Prisma.FlowerOrderByWithAggregationInput | Prisma.FlowerOrderByWithAggregationInput[]
  by: Prisma.FlowerScalarFieldEnum[] | Prisma.FlowerScalarFieldEnum
  having?: Prisma.FlowerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FlowerCountAggregateInputType | true
  _avg?: FlowerAvgAggregateInputType
  _sum?: FlowerSumAggregateInputType
  _min?: FlowerMinAggregateInputType
  _max?: FlowerMaxAggregateInputType
}

export type FlowerGroupByOutputType = {
  id: string
  name: string
  unitType: $Enums.UnitType
  stockQuantity: number
  lowStockLevel: number
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  _count: FlowerCountAggregateOutputType | null
  _avg: FlowerAvgAggregateOutputType | null
  _sum: FlowerSumAggregateOutputType | null
  _min: FlowerMinAggregateOutputType | null
  _max: FlowerMaxAggregateOutputType | null
}

type GetFlowerGroupByPayload<T extends FlowerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FlowerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FlowerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FlowerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FlowerGroupByOutputType[P]>
      }
    >
  >



export type FlowerWhereInput = {
  AND?: Prisma.FlowerWhereInput | Prisma.FlowerWhereInput[]
  OR?: Prisma.FlowerWhereInput[]
  NOT?: Prisma.FlowerWhereInput | Prisma.FlowerWhereInput[]
  id?: Prisma.StringFilter<"Flower"> | string
  name?: Prisma.StringFilter<"Flower"> | string
  unitType?: Prisma.EnumUnitTypeFilter<"Flower"> | $Enums.UnitType
  stockQuantity?: Prisma.IntFilter<"Flower"> | number
  lowStockLevel?: Prisma.IntFilter<"Flower"> | number
  isActive?: Prisma.BoolFilter<"Flower"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Flower"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Flower"> | Date | string
  usages?: Prisma.OrderFlowerUsageListRelationFilter
  stockEvents?: Prisma.StockEventListRelationFilter
}

export type FlowerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  unitType?: Prisma.SortOrder
  stockQuantity?: Prisma.SortOrder
  lowStockLevel?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  usages?: Prisma.OrderFlowerUsageOrderByRelationAggregateInput
  stockEvents?: Prisma.StockEventOrderByRelationAggregateInput
  _relevance?: Prisma.FlowerOrderByRelevanceInput
}

export type FlowerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.FlowerWhereInput | Prisma.FlowerWhereInput[]
  OR?: Prisma.FlowerWhereInput[]
  NOT?: Prisma.FlowerWhereInput | Prisma.FlowerWhereInput[]
  unitType?: Prisma.EnumUnitTypeFilter<"Flower"> | $Enums.UnitType
  stockQuantity?: Prisma.IntFilter<"Flower"> | number
  lowStockLevel?: Prisma.IntFilter<"Flower"> | number
  isActive?: Prisma.BoolFilter<"Flower"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Flower"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Flower"> | Date | string
  usages?: Prisma.OrderFlowerUsageListRelationFilter
  stockEvents?: Prisma.StockEventListRelationFilter
}, "id" | "name">

export type FlowerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  unitType?: Prisma.SortOrder
  stockQuantity?: Prisma.SortOrder
  lowStockLevel?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.FlowerCountOrderByAggregateInput
  _avg?: Prisma.FlowerAvgOrderByAggregateInput
  _max?: Prisma.FlowerMaxOrderByAggregateInput
  _min?: Prisma.FlowerMinOrderByAggregateInput
  _sum?: Prisma.FlowerSumOrderByAggregateInput
}

export type FlowerScalarWhereWithAggregatesInput = {
  AND?: Prisma.FlowerScalarWhereWithAggregatesInput | Prisma.FlowerScalarWhereWithAggregatesInput[]
  OR?: Prisma.FlowerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FlowerScalarWhereWithAggregatesInput | Prisma.FlowerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Flower"> | string
  name?: Prisma.StringWithAggregatesFilter<"Flower"> | string
  unitType?: Prisma.EnumUnitTypeWithAggregatesFilter<"Flower"> | $Enums.UnitType
  stockQuantity?: Prisma.IntWithAggregatesFilter<"Flower"> | number
  lowStockLevel?: Prisma.IntWithAggregatesFilter<"Flower"> | number
  isActive?: Prisma.BoolWithAggregatesFilter<"Flower"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Flower"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Flower"> | Date | string
}

export type FlowerCreateInput = {
  id?: string
  name: string
  unitType: $Enums.UnitType
  stockQuantity?: number
  lowStockLevel?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  usages?: Prisma.OrderFlowerUsageCreateNestedManyWithoutFlowerInput
  stockEvents?: Prisma.StockEventCreateNestedManyWithoutFlowerInput
}

export type FlowerUncheckedCreateInput = {
  id?: string
  name: string
  unitType: $Enums.UnitType
  stockQuantity?: number
  lowStockLevel?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  usages?: Prisma.OrderFlowerUsageUncheckedCreateNestedManyWithoutFlowerInput
  stockEvents?: Prisma.StockEventUncheckedCreateNestedManyWithoutFlowerInput
}

export type FlowerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  stockQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  lowStockLevel?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usages?: Prisma.OrderFlowerUsageUpdateManyWithoutFlowerNestedInput
  stockEvents?: Prisma.StockEventUpdateManyWithoutFlowerNestedInput
}

export type FlowerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  stockQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  lowStockLevel?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usages?: Prisma.OrderFlowerUsageUncheckedUpdateManyWithoutFlowerNestedInput
  stockEvents?: Prisma.StockEventUncheckedUpdateManyWithoutFlowerNestedInput
}

export type FlowerCreateManyInput = {
  id?: string
  name: string
  unitType: $Enums.UnitType
  stockQuantity?: number
  lowStockLevel?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FlowerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  stockQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  lowStockLevel?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FlowerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  stockQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  lowStockLevel?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FlowerOrderByRelevanceInput = {
  fields: Prisma.FlowerOrderByRelevanceFieldEnum | Prisma.FlowerOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type FlowerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  unitType?: Prisma.SortOrder
  stockQuantity?: Prisma.SortOrder
  lowStockLevel?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FlowerAvgOrderByAggregateInput = {
  stockQuantity?: Prisma.SortOrder
  lowStockLevel?: Prisma.SortOrder
}

export type FlowerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  unitType?: Prisma.SortOrder
  stockQuantity?: Prisma.SortOrder
  lowStockLevel?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FlowerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  unitType?: Prisma.SortOrder
  stockQuantity?: Prisma.SortOrder
  lowStockLevel?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FlowerSumOrderByAggregateInput = {
  stockQuantity?: Prisma.SortOrder
  lowStockLevel?: Prisma.SortOrder
}

export type FlowerScalarRelationFilter = {
  is?: Prisma.FlowerWhereInput
  isNot?: Prisma.FlowerWhereInput
}

export type EnumUnitTypeFieldUpdateOperationsInput = {
  set?: $Enums.UnitType
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type FlowerCreateNestedOneWithoutUsagesInput = {
  create?: Prisma.XOR<Prisma.FlowerCreateWithoutUsagesInput, Prisma.FlowerUncheckedCreateWithoutUsagesInput>
  connectOrCreate?: Prisma.FlowerCreateOrConnectWithoutUsagesInput
  connect?: Prisma.FlowerWhereUniqueInput
}

export type FlowerUpdateOneRequiredWithoutUsagesNestedInput = {
  create?: Prisma.XOR<Prisma.FlowerCreateWithoutUsagesInput, Prisma.FlowerUncheckedCreateWithoutUsagesInput>
  connectOrCreate?: Prisma.FlowerCreateOrConnectWithoutUsagesInput
  upsert?: Prisma.FlowerUpsertWithoutUsagesInput
  connect?: Prisma.FlowerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FlowerUpdateToOneWithWhereWithoutUsagesInput, Prisma.FlowerUpdateWithoutUsagesInput>, Prisma.FlowerUncheckedUpdateWithoutUsagesInput>
}

export type FlowerCreateNestedOneWithoutStockEventsInput = {
  create?: Prisma.XOR<Prisma.FlowerCreateWithoutStockEventsInput, Prisma.FlowerUncheckedCreateWithoutStockEventsInput>
  connectOrCreate?: Prisma.FlowerCreateOrConnectWithoutStockEventsInput
  connect?: Prisma.FlowerWhereUniqueInput
}

export type FlowerUpdateOneRequiredWithoutStockEventsNestedInput = {
  create?: Prisma.XOR<Prisma.FlowerCreateWithoutStockEventsInput, Prisma.FlowerUncheckedCreateWithoutStockEventsInput>
  connectOrCreate?: Prisma.FlowerCreateOrConnectWithoutStockEventsInput
  upsert?: Prisma.FlowerUpsertWithoutStockEventsInput
  connect?: Prisma.FlowerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FlowerUpdateToOneWithWhereWithoutStockEventsInput, Prisma.FlowerUpdateWithoutStockEventsInput>, Prisma.FlowerUncheckedUpdateWithoutStockEventsInput>
}

export type FlowerCreateWithoutUsagesInput = {
  id?: string
  name: string
  unitType: $Enums.UnitType
  stockQuantity?: number
  lowStockLevel?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  stockEvents?: Prisma.StockEventCreateNestedManyWithoutFlowerInput
}

export type FlowerUncheckedCreateWithoutUsagesInput = {
  id?: string
  name: string
  unitType: $Enums.UnitType
  stockQuantity?: number
  lowStockLevel?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  stockEvents?: Prisma.StockEventUncheckedCreateNestedManyWithoutFlowerInput
}

export type FlowerCreateOrConnectWithoutUsagesInput = {
  where: Prisma.FlowerWhereUniqueInput
  create: Prisma.XOR<Prisma.FlowerCreateWithoutUsagesInput, Prisma.FlowerUncheckedCreateWithoutUsagesInput>
}

export type FlowerUpsertWithoutUsagesInput = {
  update: Prisma.XOR<Prisma.FlowerUpdateWithoutUsagesInput, Prisma.FlowerUncheckedUpdateWithoutUsagesInput>
  create: Prisma.XOR<Prisma.FlowerCreateWithoutUsagesInput, Prisma.FlowerUncheckedCreateWithoutUsagesInput>
  where?: Prisma.FlowerWhereInput
}

export type FlowerUpdateToOneWithWhereWithoutUsagesInput = {
  where?: Prisma.FlowerWhereInput
  data: Prisma.XOR<Prisma.FlowerUpdateWithoutUsagesInput, Prisma.FlowerUncheckedUpdateWithoutUsagesInput>
}

export type FlowerUpdateWithoutUsagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  stockQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  lowStockLevel?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stockEvents?: Prisma.StockEventUpdateManyWithoutFlowerNestedInput
}

export type FlowerUncheckedUpdateWithoutUsagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  stockQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  lowStockLevel?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stockEvents?: Prisma.StockEventUncheckedUpdateManyWithoutFlowerNestedInput
}

export type FlowerCreateWithoutStockEventsInput = {
  id?: string
  name: string
  unitType: $Enums.UnitType
  stockQuantity?: number
  lowStockLevel?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  usages?: Prisma.OrderFlowerUsageCreateNestedManyWithoutFlowerInput
}

export type FlowerUncheckedCreateWithoutStockEventsInput = {
  id?: string
  name: string
  unitType: $Enums.UnitType
  stockQuantity?: number
  lowStockLevel?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  usages?: Prisma.OrderFlowerUsageUncheckedCreateNestedManyWithoutFlowerInput
}

export type FlowerCreateOrConnectWithoutStockEventsInput = {
  where: Prisma.FlowerWhereUniqueInput
  create: Prisma.XOR<Prisma.FlowerCreateWithoutStockEventsInput, Prisma.FlowerUncheckedCreateWithoutStockEventsInput>
}

export type FlowerUpsertWithoutStockEventsInput = {
  update: Prisma.XOR<Prisma.FlowerUpdateWithoutStockEventsInput, Prisma.FlowerUncheckedUpdateWithoutStockEventsInput>
  create: Prisma.XOR<Prisma.FlowerCreateWithoutStockEventsInput, Prisma.FlowerUncheckedCreateWithoutStockEventsInput>
  where?: Prisma.FlowerWhereInput
}

export type FlowerUpdateToOneWithWhereWithoutStockEventsInput = {
  where?: Prisma.FlowerWhereInput
  data: Prisma.XOR<Prisma.FlowerUpdateWithoutStockEventsInput, Prisma.FlowerUncheckedUpdateWithoutStockEventsInput>
}

export type FlowerUpdateWithoutStockEventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  stockQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  lowStockLevel?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usages?: Prisma.OrderFlowerUsageUpdateManyWithoutFlowerNestedInput
}

export type FlowerUncheckedUpdateWithoutStockEventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  stockQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  lowStockLevel?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usages?: Prisma.OrderFlowerUsageUncheckedUpdateManyWithoutFlowerNestedInput
}


/**
 * Count Type FlowerCountOutputType
 */

export type FlowerCountOutputType = {
  usages: number
  stockEvents: number
}

export type FlowerCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usages?: boolean | FlowerCountOutputTypeCountUsagesArgs
  stockEvents?: boolean | FlowerCountOutputTypeCountStockEventsArgs
}

/**
 * FlowerCountOutputType without action
 */
export type FlowerCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlowerCountOutputType
   */
  select?: Prisma.FlowerCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FlowerCountOutputType without action
 */
export type FlowerCountOutputTypeCountUsagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderFlowerUsageWhereInput
}

/**
 * FlowerCountOutputType without action
 */
export type FlowerCountOutputTypeCountStockEventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StockEventWhereInput
}


export type FlowerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  unitType?: boolean
  stockQuantity?: boolean
  lowStockLevel?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  usages?: boolean | Prisma.Flower$usagesArgs<ExtArgs>
  stockEvents?: boolean | Prisma.Flower$stockEventsArgs<ExtArgs>
  _count?: boolean | Prisma.FlowerCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["flower"]>



export type FlowerSelectScalar = {
  id?: boolean
  name?: boolean
  unitType?: boolean
  stockQuantity?: boolean
  lowStockLevel?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type FlowerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "unitType" | "stockQuantity" | "lowStockLevel" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["flower"]>
export type FlowerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usages?: boolean | Prisma.Flower$usagesArgs<ExtArgs>
  stockEvents?: boolean | Prisma.Flower$stockEventsArgs<ExtArgs>
  _count?: boolean | Prisma.FlowerCountOutputTypeDefaultArgs<ExtArgs>
}

export type $FlowerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Flower"
  objects: {
    usages: Prisma.$OrderFlowerUsagePayload<ExtArgs>[]
    stockEvents: Prisma.$StockEventPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    unitType: $Enums.UnitType
    stockQuantity: number
    lowStockLevel: number
    isActive: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["flower"]>
  composites: {}
}

export type FlowerGetPayload<S extends boolean | null | undefined | FlowerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FlowerPayload, S>

export type FlowerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FlowerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FlowerCountAggregateInputType | true
  }

export interface FlowerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Flower'], meta: { name: 'Flower' } }
  /**
   * Find zero or one Flower that matches the filter.
   * @param {FlowerFindUniqueArgs} args - Arguments to find a Flower
   * @example
   * // Get one Flower
   * const flower = await prisma.flower.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FlowerFindUniqueArgs>(args: Prisma.SelectSubset<T, FlowerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FlowerClient<runtime.Types.Result.GetResult<Prisma.$FlowerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Flower that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FlowerFindUniqueOrThrowArgs} args - Arguments to find a Flower
   * @example
   * // Get one Flower
   * const flower = await prisma.flower.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FlowerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FlowerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FlowerClient<runtime.Types.Result.GetResult<Prisma.$FlowerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Flower that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlowerFindFirstArgs} args - Arguments to find a Flower
   * @example
   * // Get one Flower
   * const flower = await prisma.flower.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FlowerFindFirstArgs>(args?: Prisma.SelectSubset<T, FlowerFindFirstArgs<ExtArgs>>): Prisma.Prisma__FlowerClient<runtime.Types.Result.GetResult<Prisma.$FlowerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Flower that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlowerFindFirstOrThrowArgs} args - Arguments to find a Flower
   * @example
   * // Get one Flower
   * const flower = await prisma.flower.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FlowerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FlowerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FlowerClient<runtime.Types.Result.GetResult<Prisma.$FlowerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Flowers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlowerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Flowers
   * const flowers = await prisma.flower.findMany()
   * 
   * // Get first 10 Flowers
   * const flowers = await prisma.flower.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const flowerWithIdOnly = await prisma.flower.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FlowerFindManyArgs>(args?: Prisma.SelectSubset<T, FlowerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FlowerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Flower.
   * @param {FlowerCreateArgs} args - Arguments to create a Flower.
   * @example
   * // Create one Flower
   * const Flower = await prisma.flower.create({
   *   data: {
   *     // ... data to create a Flower
   *   }
   * })
   * 
   */
  create<T extends FlowerCreateArgs>(args: Prisma.SelectSubset<T, FlowerCreateArgs<ExtArgs>>): Prisma.Prisma__FlowerClient<runtime.Types.Result.GetResult<Prisma.$FlowerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Flowers.
   * @param {FlowerCreateManyArgs} args - Arguments to create many Flowers.
   * @example
   * // Create many Flowers
   * const flower = await prisma.flower.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FlowerCreateManyArgs>(args?: Prisma.SelectSubset<T, FlowerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Flower.
   * @param {FlowerDeleteArgs} args - Arguments to delete one Flower.
   * @example
   * // Delete one Flower
   * const Flower = await prisma.flower.delete({
   *   where: {
   *     // ... filter to delete one Flower
   *   }
   * })
   * 
   */
  delete<T extends FlowerDeleteArgs>(args: Prisma.SelectSubset<T, FlowerDeleteArgs<ExtArgs>>): Prisma.Prisma__FlowerClient<runtime.Types.Result.GetResult<Prisma.$FlowerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Flower.
   * @param {FlowerUpdateArgs} args - Arguments to update one Flower.
   * @example
   * // Update one Flower
   * const flower = await prisma.flower.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FlowerUpdateArgs>(args: Prisma.SelectSubset<T, FlowerUpdateArgs<ExtArgs>>): Prisma.Prisma__FlowerClient<runtime.Types.Result.GetResult<Prisma.$FlowerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Flowers.
   * @param {FlowerDeleteManyArgs} args - Arguments to filter Flowers to delete.
   * @example
   * // Delete a few Flowers
   * const { count } = await prisma.flower.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FlowerDeleteManyArgs>(args?: Prisma.SelectSubset<T, FlowerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Flowers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlowerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Flowers
   * const flower = await prisma.flower.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FlowerUpdateManyArgs>(args: Prisma.SelectSubset<T, FlowerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Flower.
   * @param {FlowerUpsertArgs} args - Arguments to update or create a Flower.
   * @example
   * // Update or create a Flower
   * const flower = await prisma.flower.upsert({
   *   create: {
   *     // ... data to create a Flower
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Flower we want to update
   *   }
   * })
   */
  upsert<T extends FlowerUpsertArgs>(args: Prisma.SelectSubset<T, FlowerUpsertArgs<ExtArgs>>): Prisma.Prisma__FlowerClient<runtime.Types.Result.GetResult<Prisma.$FlowerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Flowers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlowerCountArgs} args - Arguments to filter Flowers to count.
   * @example
   * // Count the number of Flowers
   * const count = await prisma.flower.count({
   *   where: {
   *     // ... the filter for the Flowers we want to count
   *   }
   * })
  **/
  count<T extends FlowerCountArgs>(
    args?: Prisma.Subset<T, FlowerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FlowerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Flower.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlowerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FlowerAggregateArgs>(args: Prisma.Subset<T, FlowerAggregateArgs>): Prisma.PrismaPromise<GetFlowerAggregateType<T>>

  /**
   * Group by Flower.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlowerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FlowerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FlowerGroupByArgs['orderBy'] }
      : { orderBy?: FlowerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FlowerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFlowerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Flower model
 */
readonly fields: FlowerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Flower.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FlowerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  usages<T extends Prisma.Flower$usagesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Flower$usagesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderFlowerUsagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  stockEvents<T extends Prisma.Flower$stockEventsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Flower$stockEventsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StockEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Flower model
 */
export interface FlowerFieldRefs {
  readonly id: Prisma.FieldRef<"Flower", 'String'>
  readonly name: Prisma.FieldRef<"Flower", 'String'>
  readonly unitType: Prisma.FieldRef<"Flower", 'UnitType'>
  readonly stockQuantity: Prisma.FieldRef<"Flower", 'Int'>
  readonly lowStockLevel: Prisma.FieldRef<"Flower", 'Int'>
  readonly isActive: Prisma.FieldRef<"Flower", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Flower", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Flower", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Flower findUnique
 */
export type FlowerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flower
   */
  select?: Prisma.FlowerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Flower
   */
  omit?: Prisma.FlowerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlowerInclude<ExtArgs> | null
  /**
   * Filter, which Flower to fetch.
   */
  where: Prisma.FlowerWhereUniqueInput
}

/**
 * Flower findUniqueOrThrow
 */
export type FlowerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flower
   */
  select?: Prisma.FlowerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Flower
   */
  omit?: Prisma.FlowerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlowerInclude<ExtArgs> | null
  /**
   * Filter, which Flower to fetch.
   */
  where: Prisma.FlowerWhereUniqueInput
}

/**
 * Flower findFirst
 */
export type FlowerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flower
   */
  select?: Prisma.FlowerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Flower
   */
  omit?: Prisma.FlowerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlowerInclude<ExtArgs> | null
  /**
   * Filter, which Flower to fetch.
   */
  where?: Prisma.FlowerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Flowers to fetch.
   */
  orderBy?: Prisma.FlowerOrderByWithRelationInput | Prisma.FlowerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Flowers.
   */
  cursor?: Prisma.FlowerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Flowers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Flowers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Flowers.
   */
  distinct?: Prisma.FlowerScalarFieldEnum | Prisma.FlowerScalarFieldEnum[]
}

/**
 * Flower findFirstOrThrow
 */
export type FlowerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flower
   */
  select?: Prisma.FlowerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Flower
   */
  omit?: Prisma.FlowerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlowerInclude<ExtArgs> | null
  /**
   * Filter, which Flower to fetch.
   */
  where?: Prisma.FlowerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Flowers to fetch.
   */
  orderBy?: Prisma.FlowerOrderByWithRelationInput | Prisma.FlowerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Flowers.
   */
  cursor?: Prisma.FlowerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Flowers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Flowers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Flowers.
   */
  distinct?: Prisma.FlowerScalarFieldEnum | Prisma.FlowerScalarFieldEnum[]
}

/**
 * Flower findMany
 */
export type FlowerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flower
   */
  select?: Prisma.FlowerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Flower
   */
  omit?: Prisma.FlowerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlowerInclude<ExtArgs> | null
  /**
   * Filter, which Flowers to fetch.
   */
  where?: Prisma.FlowerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Flowers to fetch.
   */
  orderBy?: Prisma.FlowerOrderByWithRelationInput | Prisma.FlowerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Flowers.
   */
  cursor?: Prisma.FlowerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Flowers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Flowers.
   */
  skip?: number
  distinct?: Prisma.FlowerScalarFieldEnum | Prisma.FlowerScalarFieldEnum[]
}

/**
 * Flower create
 */
export type FlowerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flower
   */
  select?: Prisma.FlowerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Flower
   */
  omit?: Prisma.FlowerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlowerInclude<ExtArgs> | null
  /**
   * The data needed to create a Flower.
   */
  data: Prisma.XOR<Prisma.FlowerCreateInput, Prisma.FlowerUncheckedCreateInput>
}

/**
 * Flower createMany
 */
export type FlowerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Flowers.
   */
  data: Prisma.FlowerCreateManyInput | Prisma.FlowerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Flower update
 */
export type FlowerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flower
   */
  select?: Prisma.FlowerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Flower
   */
  omit?: Prisma.FlowerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlowerInclude<ExtArgs> | null
  /**
   * The data needed to update a Flower.
   */
  data: Prisma.XOR<Prisma.FlowerUpdateInput, Prisma.FlowerUncheckedUpdateInput>
  /**
   * Choose, which Flower to update.
   */
  where: Prisma.FlowerWhereUniqueInput
}

/**
 * Flower updateMany
 */
export type FlowerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Flowers.
   */
  data: Prisma.XOR<Prisma.FlowerUpdateManyMutationInput, Prisma.FlowerUncheckedUpdateManyInput>
  /**
   * Filter which Flowers to update
   */
  where?: Prisma.FlowerWhereInput
  /**
   * Limit how many Flowers to update.
   */
  limit?: number
}

/**
 * Flower upsert
 */
export type FlowerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flower
   */
  select?: Prisma.FlowerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Flower
   */
  omit?: Prisma.FlowerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlowerInclude<ExtArgs> | null
  /**
   * The filter to search for the Flower to update in case it exists.
   */
  where: Prisma.FlowerWhereUniqueInput
  /**
   * In case the Flower found by the `where` argument doesn't exist, create a new Flower with this data.
   */
  create: Prisma.XOR<Prisma.FlowerCreateInput, Prisma.FlowerUncheckedCreateInput>
  /**
   * In case the Flower was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FlowerUpdateInput, Prisma.FlowerUncheckedUpdateInput>
}

/**
 * Flower delete
 */
export type FlowerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flower
   */
  select?: Prisma.FlowerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Flower
   */
  omit?: Prisma.FlowerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlowerInclude<ExtArgs> | null
  /**
   * Filter which Flower to delete.
   */
  where: Prisma.FlowerWhereUniqueInput
}

/**
 * Flower deleteMany
 */
export type FlowerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Flowers to delete
   */
  where?: Prisma.FlowerWhereInput
  /**
   * Limit how many Flowers to delete.
   */
  limit?: number
}

/**
 * Flower.usages
 */
export type Flower$usagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderFlowerUsage
   */
  select?: Prisma.OrderFlowerUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderFlowerUsage
   */
  omit?: Prisma.OrderFlowerUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderFlowerUsageInclude<ExtArgs> | null
  where?: Prisma.OrderFlowerUsageWhereInput
  orderBy?: Prisma.OrderFlowerUsageOrderByWithRelationInput | Prisma.OrderFlowerUsageOrderByWithRelationInput[]
  cursor?: Prisma.OrderFlowerUsageWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrderFlowerUsageScalarFieldEnum | Prisma.OrderFlowerUsageScalarFieldEnum[]
}

/**
 * Flower.stockEvents
 */
export type Flower$stockEventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockEvent
   */
  select?: Prisma.StockEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockEvent
   */
  omit?: Prisma.StockEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockEventInclude<ExtArgs> | null
  where?: Prisma.StockEventWhereInput
  orderBy?: Prisma.StockEventOrderByWithRelationInput | Prisma.StockEventOrderByWithRelationInput[]
  cursor?: Prisma.StockEventWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.StockEventScalarFieldEnum | Prisma.StockEventScalarFieldEnum[]
}

/**
 * Flower without action
 */
export type FlowerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Flower
   */
  select?: Prisma.FlowerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Flower
   */
  omit?: Prisma.FlowerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FlowerInclude<ExtArgs> | null
}
