
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `OrderFlowerUsage` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model OrderFlowerUsage
 * 
 */
export type OrderFlowerUsageModel = runtime.Types.Result.DefaultSelection<Prisma.$OrderFlowerUsagePayload>

export type AggregateOrderFlowerUsage = {
  _count: OrderFlowerUsageCountAggregateOutputType | null
  _avg: OrderFlowerUsageAvgAggregateOutputType | null
  _sum: OrderFlowerUsageSumAggregateOutputType | null
  _min: OrderFlowerUsageMinAggregateOutputType | null
  _max: OrderFlowerUsageMaxAggregateOutputType | null
}

export type OrderFlowerUsageAvgAggregateOutputType = {
  quantity: number | null
}

export type OrderFlowerUsageSumAggregateOutputType = {
  quantity: number | null
}

export type OrderFlowerUsageMinAggregateOutputType = {
  id: string | null
  orderId: string | null
  flowerId: string | null
  quantity: number | null
  unitType: $Enums.UnitType | null
  createdAt: Date | null
}

export type OrderFlowerUsageMaxAggregateOutputType = {
  id: string | null
  orderId: string | null
  flowerId: string | null
  quantity: number | null
  unitType: $Enums.UnitType | null
  createdAt: Date | null
}

export type OrderFlowerUsageCountAggregateOutputType = {
  id: number
  orderId: number
  flowerId: number
  quantity: number
  unitType: number
  createdAt: number
  _all: number
}


export type OrderFlowerUsageAvgAggregateInputType = {
  quantity?: true
}

export type OrderFlowerUsageSumAggregateInputType = {
  quantity?: true
}

export type OrderFlowerUsageMinAggregateInputType = {
  id?: true
  orderId?: true
  flowerId?: true
  quantity?: true
  unitType?: true
  createdAt?: true
}

export type OrderFlowerUsageMaxAggregateInputType = {
  id?: true
  orderId?: true
  flowerId?: true
  quantity?: true
  unitType?: true
  createdAt?: true
}

export type OrderFlowerUsageCountAggregateInputType = {
  id?: true
  orderId?: true
  flowerId?: true
  quantity?: true
  unitType?: true
  createdAt?: true
  _all?: true
}

export type OrderFlowerUsageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OrderFlowerUsage to aggregate.
   */
  where?: Prisma.OrderFlowerUsageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrderFlowerUsages to fetch.
   */
  orderBy?: Prisma.OrderFlowerUsageOrderByWithRelationInput | Prisma.OrderFlowerUsageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.OrderFlowerUsageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrderFlowerUsages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrderFlowerUsages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned OrderFlowerUsages
  **/
  _count?: true | OrderFlowerUsageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: OrderFlowerUsageAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: OrderFlowerUsageSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OrderFlowerUsageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OrderFlowerUsageMaxAggregateInputType
}

export type GetOrderFlowerUsageAggregateType<T extends OrderFlowerUsageAggregateArgs> = {
      [P in keyof T & keyof AggregateOrderFlowerUsage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrderFlowerUsage[P]>
    : Prisma.GetScalarType<T[P], AggregateOrderFlowerUsage[P]>
}




export type OrderFlowerUsageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderFlowerUsageWhereInput
  orderBy?: Prisma.OrderFlowerUsageOrderByWithAggregationInput | Prisma.OrderFlowerUsageOrderByWithAggregationInput[]
  by: Prisma.OrderFlowerUsageScalarFieldEnum[] | Prisma.OrderFlowerUsageScalarFieldEnum
  having?: Prisma.OrderFlowerUsageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OrderFlowerUsageCountAggregateInputType | true
  _avg?: OrderFlowerUsageAvgAggregateInputType
  _sum?: OrderFlowerUsageSumAggregateInputType
  _min?: OrderFlowerUsageMinAggregateInputType
  _max?: OrderFlowerUsageMaxAggregateInputType
}

export type OrderFlowerUsageGroupByOutputType = {
  id: string
  orderId: string
  flowerId: string
  quantity: number
  unitType: $Enums.UnitType
  createdAt: Date
  _count: OrderFlowerUsageCountAggregateOutputType | null
  _avg: OrderFlowerUsageAvgAggregateOutputType | null
  _sum: OrderFlowerUsageSumAggregateOutputType | null
  _min: OrderFlowerUsageMinAggregateOutputType | null
  _max: OrderFlowerUsageMaxAggregateOutputType | null
}

type GetOrderFlowerUsageGroupByPayload<T extends OrderFlowerUsageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OrderFlowerUsageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OrderFlowerUsageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OrderFlowerUsageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OrderFlowerUsageGroupByOutputType[P]>
      }
    >
  >



export type OrderFlowerUsageWhereInput = {
  AND?: Prisma.OrderFlowerUsageWhereInput | Prisma.OrderFlowerUsageWhereInput[]
  OR?: Prisma.OrderFlowerUsageWhereInput[]
  NOT?: Prisma.OrderFlowerUsageWhereInput | Prisma.OrderFlowerUsageWhereInput[]
  id?: Prisma.StringFilter<"OrderFlowerUsage"> | string
  orderId?: Prisma.StringFilter<"OrderFlowerUsage"> | string
  flowerId?: Prisma.StringFilter<"OrderFlowerUsage"> | string
  quantity?: Prisma.IntFilter<"OrderFlowerUsage"> | number
  unitType?: Prisma.EnumUnitTypeFilter<"OrderFlowerUsage"> | $Enums.UnitType
  createdAt?: Prisma.DateTimeFilter<"OrderFlowerUsage"> | Date | string
  order?: Prisma.XOR<Prisma.OrderScalarRelationFilter, Prisma.OrderWhereInput>
  flower?: Prisma.XOR<Prisma.FlowerScalarRelationFilter, Prisma.FlowerWhereInput>
}

export type OrderFlowerUsageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  flowerId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  order?: Prisma.OrderOrderByWithRelationInput
  flower?: Prisma.FlowerOrderByWithRelationInput
  _relevance?: Prisma.OrderFlowerUsageOrderByRelevanceInput
}

export type OrderFlowerUsageWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  orderId_flowerId?: Prisma.OrderFlowerUsageOrderIdFlowerIdCompoundUniqueInput
  AND?: Prisma.OrderFlowerUsageWhereInput | Prisma.OrderFlowerUsageWhereInput[]
  OR?: Prisma.OrderFlowerUsageWhereInput[]
  NOT?: Prisma.OrderFlowerUsageWhereInput | Prisma.OrderFlowerUsageWhereInput[]
  orderId?: Prisma.StringFilter<"OrderFlowerUsage"> | string
  flowerId?: Prisma.StringFilter<"OrderFlowerUsage"> | string
  quantity?: Prisma.IntFilter<"OrderFlowerUsage"> | number
  unitType?: Prisma.EnumUnitTypeFilter<"OrderFlowerUsage"> | $Enums.UnitType
  createdAt?: Prisma.DateTimeFilter<"OrderFlowerUsage"> | Date | string
  order?: Prisma.XOR<Prisma.OrderScalarRelationFilter, Prisma.OrderWhereInput>
  flower?: Prisma.XOR<Prisma.FlowerScalarRelationFilter, Prisma.FlowerWhereInput>
}, "id" | "orderId_flowerId">

export type OrderFlowerUsageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  flowerId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.OrderFlowerUsageCountOrderByAggregateInput
  _avg?: Prisma.OrderFlowerUsageAvgOrderByAggregateInput
  _max?: Prisma.OrderFlowerUsageMaxOrderByAggregateInput
  _min?: Prisma.OrderFlowerUsageMinOrderByAggregateInput
  _sum?: Prisma.OrderFlowerUsageSumOrderByAggregateInput
}

export type OrderFlowerUsageScalarWhereWithAggregatesInput = {
  AND?: Prisma.OrderFlowerUsageScalarWhereWithAggregatesInput | Prisma.OrderFlowerUsageScalarWhereWithAggregatesInput[]
  OR?: Prisma.OrderFlowerUsageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OrderFlowerUsageScalarWhereWithAggregatesInput | Prisma.OrderFlowerUsageScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"OrderFlowerUsage"> | string
  orderId?: Prisma.StringWithAggregatesFilter<"OrderFlowerUsage"> | string
  flowerId?: Prisma.StringWithAggregatesFilter<"OrderFlowerUsage"> | string
  quantity?: Prisma.IntWithAggregatesFilter<"OrderFlowerUsage"> | number
  unitType?: Prisma.EnumUnitTypeWithAggregatesFilter<"OrderFlowerUsage"> | $Enums.UnitType
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"OrderFlowerUsage"> | Date | string
}

export type OrderFlowerUsageCreateInput = {
  id?: string
  quantity: number
  unitType: $Enums.UnitType
  createdAt?: Date | string
  order: Prisma.OrderCreateNestedOneWithoutFlowerUsagesInput
  flower: Prisma.FlowerCreateNestedOneWithoutUsagesInput
}

export type OrderFlowerUsageUncheckedCreateInput = {
  id?: string
  orderId: string
  flowerId: string
  quantity: number
  unitType: $Enums.UnitType
  createdAt?: Date | string
}

export type OrderFlowerUsageUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.OrderUpdateOneRequiredWithoutFlowerUsagesNestedInput
  flower?: Prisma.FlowerUpdateOneRequiredWithoutUsagesNestedInput
}

export type OrderFlowerUsageUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  flowerId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrderFlowerUsageCreateManyInput = {
  id?: string
  orderId: string
  flowerId: string
  quantity: number
  unitType: $Enums.UnitType
  createdAt?: Date | string
}

export type OrderFlowerUsageUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrderFlowerUsageUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  flowerId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrderFlowerUsageListRelationFilter = {
  every?: Prisma.OrderFlowerUsageWhereInput
  some?: Prisma.OrderFlowerUsageWhereInput
  none?: Prisma.OrderFlowerUsageWhereInput
}

export type OrderFlowerUsageOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type OrderFlowerUsageOrderByRelevanceInput = {
  fields: Prisma.OrderFlowerUsageOrderByRelevanceFieldEnum | Prisma.OrderFlowerUsageOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type OrderFlowerUsageOrderIdFlowerIdCompoundUniqueInput = {
  orderId: string
  flowerId: string
}

export type OrderFlowerUsageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  flowerId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type OrderFlowerUsageAvgOrderByAggregateInput = {
  quantity?: Prisma.SortOrder
}

export type OrderFlowerUsageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  flowerId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type OrderFlowerUsageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  flowerId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type OrderFlowerUsageSumOrderByAggregateInput = {
  quantity?: Prisma.SortOrder
}

export type OrderFlowerUsageCreateNestedManyWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.OrderFlowerUsageCreateWithoutOrderInput, Prisma.OrderFlowerUsageUncheckedCreateWithoutOrderInput> | Prisma.OrderFlowerUsageCreateWithoutOrderInput[] | Prisma.OrderFlowerUsageUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.OrderFlowerUsageCreateOrConnectWithoutOrderInput | Prisma.OrderFlowerUsageCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.OrderFlowerUsageCreateManyOrderInputEnvelope
  connect?: Prisma.OrderFlowerUsageWhereUniqueInput | Prisma.OrderFlowerUsageWhereUniqueInput[]
}

export type OrderFlowerUsageUncheckedCreateNestedManyWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.OrderFlowerUsageCreateWithoutOrderInput, Prisma.OrderFlowerUsageUncheckedCreateWithoutOrderInput> | Prisma.OrderFlowerUsageCreateWithoutOrderInput[] | Prisma.OrderFlowerUsageUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.OrderFlowerUsageCreateOrConnectWithoutOrderInput | Prisma.OrderFlowerUsageCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.OrderFlowerUsageCreateManyOrderInputEnvelope
  connect?: Prisma.OrderFlowerUsageWhereUniqueInput | Prisma.OrderFlowerUsageWhereUniqueInput[]
}

export type OrderFlowerUsageUpdateManyWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.OrderFlowerUsageCreateWithoutOrderInput, Prisma.OrderFlowerUsageUncheckedCreateWithoutOrderInput> | Prisma.OrderFlowerUsageCreateWithoutOrderInput[] | Prisma.OrderFlowerUsageUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.OrderFlowerUsageCreateOrConnectWithoutOrderInput | Prisma.OrderFlowerUsageCreateOrConnectWithoutOrderInput[]
  upsert?: Prisma.OrderFlowerUsageUpsertWithWhereUniqueWithoutOrderInput | Prisma.OrderFlowerUsageUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.OrderFlowerUsageCreateManyOrderInputEnvelope
  set?: Prisma.OrderFlowerUsageWhereUniqueInput | Prisma.OrderFlowerUsageWhereUniqueInput[]
  disconnect?: Prisma.OrderFlowerUsageWhereUniqueInput | Prisma.OrderFlowerUsageWhereUniqueInput[]
  delete?: Prisma.OrderFlowerUsageWhereUniqueInput | Prisma.OrderFlowerUsageWhereUniqueInput[]
  connect?: Prisma.OrderFlowerUsageWhereUniqueInput | Prisma.OrderFlowerUsageWhereUniqueInput[]
  update?: Prisma.OrderFlowerUsageUpdateWithWhereUniqueWithoutOrderInput | Prisma.OrderFlowerUsageUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?: Prisma.OrderFlowerUsageUpdateManyWithWhereWithoutOrderInput | Prisma.OrderFlowerUsageUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?: Prisma.OrderFlowerUsageScalarWhereInput | Prisma.OrderFlowerUsageScalarWhereInput[]
}

export type OrderFlowerUsageUncheckedUpdateManyWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.OrderFlowerUsageCreateWithoutOrderInput, Prisma.OrderFlowerUsageUncheckedCreateWithoutOrderInput> | Prisma.OrderFlowerUsageCreateWithoutOrderInput[] | Prisma.OrderFlowerUsageUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.OrderFlowerUsageCreateOrConnectWithoutOrderInput | Prisma.OrderFlowerUsageCreateOrConnectWithoutOrderInput[]
  upsert?: Prisma.OrderFlowerUsageUpsertWithWhereUniqueWithoutOrderInput | Prisma.OrderFlowerUsageUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.OrderFlowerUsageCreateManyOrderInputEnvelope
  set?: Prisma.OrderFlowerUsageWhereUniqueInput | Prisma.OrderFlowerUsageWhereUniqueInput[]
  disconnect?: Prisma.OrderFlowerUsageWhereUniqueInput | Prisma.OrderFlowerUsageWhereUniqueInput[]
  delete?: Prisma.OrderFlowerUsageWhereUniqueInput | Prisma.OrderFlowerUsageWhereUniqueInput[]
  connect?: Prisma.OrderFlowerUsageWhereUniqueInput | Prisma.OrderFlowerUsageWhereUniqueInput[]
  update?: Prisma.OrderFlowerUsageUpdateWithWhereUniqueWithoutOrderInput | Prisma.OrderFlowerUsageUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?: Prisma.OrderFlowerUsageUpdateManyWithWhereWithoutOrderInput | Prisma.OrderFlowerUsageUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?: Prisma.OrderFlowerUsageScalarWhereInput | Prisma.OrderFlowerUsageScalarWhereInput[]
}

export type OrderFlowerUsageCreateNestedManyWithoutFlowerInput = {
  create?: Prisma.XOR<Prisma.OrderFlowerUsageCreateWithoutFlowerInput, Prisma.OrderFlowerUsageUncheckedCreateWithoutFlowerInput> | Prisma.OrderFlowerUsageCreateWithoutFlowerInput[] | Prisma.OrderFlowerUsageUncheckedCreateWithoutFlowerInput[]
  connectOrCreate?: Prisma.OrderFlowerUsageCreateOrConnectWithoutFlowerInput | Prisma.OrderFlowerUsageCreateOrConnectWithoutFlowerInput[]
  createMany?: Prisma.OrderFlowerUsageCreateManyFlowerInputEnvelope
  connect?: Prisma.OrderFlowerUsageWhereUniqueInput | Prisma.OrderFlowerUsageWhereUniqueInput[]
}

export type OrderFlowerUsageUncheckedCreateNestedManyWithoutFlowerInput = {
  create?: Prisma.XOR<Prisma.OrderFlowerUsageCreateWithoutFlowerInput, Prisma.OrderFlowerUsageUncheckedCreateWithoutFlowerInput> | Prisma.OrderFlowerUsageCreateWithoutFlowerInput[] | Prisma.OrderFlowerUsageUncheckedCreateWithoutFlowerInput[]
  connectOrCreate?: Prisma.OrderFlowerUsageCreateOrConnectWithoutFlowerInput | Prisma.OrderFlowerUsageCreateOrConnectWithoutFlowerInput[]
  createMany?: Prisma.OrderFlowerUsageCreateManyFlowerInputEnvelope
  connect?: Prisma.OrderFlowerUsageWhereUniqueInput | Prisma.OrderFlowerUsageWhereUniqueInput[]
}

export type OrderFlowerUsageUpdateManyWithoutFlowerNestedInput = {
  create?: Prisma.XOR<Prisma.OrderFlowerUsageCreateWithoutFlowerInput, Prisma.OrderFlowerUsageUncheckedCreateWithoutFlowerInput> | Prisma.OrderFlowerUsageCreateWithoutFlowerInput[] | Prisma.OrderFlowerUsageUncheckedCreateWithoutFlowerInput[]
  connectOrCreate?: Prisma.OrderFlowerUsageCreateOrConnectWithoutFlowerInput | Prisma.OrderFlowerUsageCreateOrConnectWithoutFlowerInput[]
  upsert?: Prisma.OrderFlowerUsageUpsertWithWhereUniqueWithoutFlowerInput | Prisma.OrderFlowerUsageUpsertWithWhereUniqueWithoutFlowerInput[]
  createMany?: Prisma.OrderFlowerUsageCreateManyFlowerInputEnvelope
  set?: Prisma.OrderFlowerUsageWhereUniqueInput | Prisma.OrderFlowerUsageWhereUniqueInput[]
  disconnect?: Prisma.OrderFlowerUsageWhereUniqueInput | Prisma.OrderFlowerUsageWhereUniqueInput[]
  delete?: Prisma.OrderFlowerUsageWhereUniqueInput | Prisma.OrderFlowerUsageWhereUniqueInput[]
  connect?: Prisma.OrderFlowerUsageWhereUniqueInput | Prisma.OrderFlowerUsageWhereUniqueInput[]
  update?: Prisma.OrderFlowerUsageUpdateWithWhereUniqueWithoutFlowerInput | Prisma.OrderFlowerUsageUpdateWithWhereUniqueWithoutFlowerInput[]
  updateMany?: Prisma.OrderFlowerUsageUpdateManyWithWhereWithoutFlowerInput | Prisma.OrderFlowerUsageUpdateManyWithWhereWithoutFlowerInput[]
  deleteMany?: Prisma.OrderFlowerUsageScalarWhereInput | Prisma.OrderFlowerUsageScalarWhereInput[]
}

export type OrderFlowerUsageUncheckedUpdateManyWithoutFlowerNestedInput = {
  create?: Prisma.XOR<Prisma.OrderFlowerUsageCreateWithoutFlowerInput, Prisma.OrderFlowerUsageUncheckedCreateWithoutFlowerInput> | Prisma.OrderFlowerUsageCreateWithoutFlowerInput[] | Prisma.OrderFlowerUsageUncheckedCreateWithoutFlowerInput[]
  connectOrCreate?: Prisma.OrderFlowerUsageCreateOrConnectWithoutFlowerInput | Prisma.OrderFlowerUsageCreateOrConnectWithoutFlowerInput[]
  upsert?: Prisma.OrderFlowerUsageUpsertWithWhereUniqueWithoutFlowerInput | Prisma.OrderFlowerUsageUpsertWithWhereUniqueWithoutFlowerInput[]
  createMany?: Prisma.OrderFlowerUsageCreateManyFlowerInputEnvelope
  set?: Prisma.OrderFlowerUsageWhereUniqueInput | Prisma.OrderFlowerUsageWhereUniqueInput[]
  disconnect?: Prisma.OrderFlowerUsageWhereUniqueInput | Prisma.OrderFlowerUsageWhereUniqueInput[]
  delete?: Prisma.OrderFlowerUsageWhereUniqueInput | Prisma.OrderFlowerUsageWhereUniqueInput[]
  connect?: Prisma.OrderFlowerUsageWhereUniqueInput | Prisma.OrderFlowerUsageWhereUniqueInput[]
  update?: Prisma.OrderFlowerUsageUpdateWithWhereUniqueWithoutFlowerInput | Prisma.OrderFlowerUsageUpdateWithWhereUniqueWithoutFlowerInput[]
  updateMany?: Prisma.OrderFlowerUsageUpdateManyWithWhereWithoutFlowerInput | Prisma.OrderFlowerUsageUpdateManyWithWhereWithoutFlowerInput[]
  deleteMany?: Prisma.OrderFlowerUsageScalarWhereInput | Prisma.OrderFlowerUsageScalarWhereInput[]
}

export type OrderFlowerUsageCreateWithoutOrderInput = {
  id?: string
  quantity: number
  unitType: $Enums.UnitType
  createdAt?: Date | string
  flower: Prisma.FlowerCreateNestedOneWithoutUsagesInput
}

export type OrderFlowerUsageUncheckedCreateWithoutOrderInput = {
  id?: string
  flowerId: string
  quantity: number
  unitType: $Enums.UnitType
  createdAt?: Date | string
}

export type OrderFlowerUsageCreateOrConnectWithoutOrderInput = {
  where: Prisma.OrderFlowerUsageWhereUniqueInput
  create: Prisma.XOR<Prisma.OrderFlowerUsageCreateWithoutOrderInput, Prisma.OrderFlowerUsageUncheckedCreateWithoutOrderInput>
}

export type OrderFlowerUsageCreateManyOrderInputEnvelope = {
  data: Prisma.OrderFlowerUsageCreateManyOrderInput | Prisma.OrderFlowerUsageCreateManyOrderInput[]
  skipDuplicates?: boolean
}

export type OrderFlowerUsageUpsertWithWhereUniqueWithoutOrderInput = {
  where: Prisma.OrderFlowerUsageWhereUniqueInput
  update: Prisma.XOR<Prisma.OrderFlowerUsageUpdateWithoutOrderInput, Prisma.OrderFlowerUsageUncheckedUpdateWithoutOrderInput>
  create: Prisma.XOR<Prisma.OrderFlowerUsageCreateWithoutOrderInput, Prisma.OrderFlowerUsageUncheckedCreateWithoutOrderInput>
}

export type OrderFlowerUsageUpdateWithWhereUniqueWithoutOrderInput = {
  where: Prisma.OrderFlowerUsageWhereUniqueInput
  data: Prisma.XOR<Prisma.OrderFlowerUsageUpdateWithoutOrderInput, Prisma.OrderFlowerUsageUncheckedUpdateWithoutOrderInput>
}

export type OrderFlowerUsageUpdateManyWithWhereWithoutOrderInput = {
  where: Prisma.OrderFlowerUsageScalarWhereInput
  data: Prisma.XOR<Prisma.OrderFlowerUsageUpdateManyMutationInput, Prisma.OrderFlowerUsageUncheckedUpdateManyWithoutOrderInput>
}

export type OrderFlowerUsageScalarWhereInput = {
  AND?: Prisma.OrderFlowerUsageScalarWhereInput | Prisma.OrderFlowerUsageScalarWhereInput[]
  OR?: Prisma.OrderFlowerUsageScalarWhereInput[]
  NOT?: Prisma.OrderFlowerUsageScalarWhereInput | Prisma.OrderFlowerUsageScalarWhereInput[]
  id?: Prisma.StringFilter<"OrderFlowerUsage"> | string
  orderId?: Prisma.StringFilter<"OrderFlowerUsage"> | string
  flowerId?: Prisma.StringFilter<"OrderFlowerUsage"> | string
  quantity?: Prisma.IntFilter<"OrderFlowerUsage"> | number
  unitType?: Prisma.EnumUnitTypeFilter<"OrderFlowerUsage"> | $Enums.UnitType
  createdAt?: Prisma.DateTimeFilter<"OrderFlowerUsage"> | Date | string
}

export type OrderFlowerUsageCreateWithoutFlowerInput = {
  id?: string
  quantity: number
  unitType: $Enums.UnitType
  createdAt?: Date | string
  order: Prisma.OrderCreateNestedOneWithoutFlowerUsagesInput
}

export type OrderFlowerUsageUncheckedCreateWithoutFlowerInput = {
  id?: string
  orderId: string
  quantity: number
  unitType: $Enums.UnitType
  createdAt?: Date | string
}

export type OrderFlowerUsageCreateOrConnectWithoutFlowerInput = {
  where: Prisma.OrderFlowerUsageWhereUniqueInput
  create: Prisma.XOR<Prisma.OrderFlowerUsageCreateWithoutFlowerInput, Prisma.OrderFlowerUsageUncheckedCreateWithoutFlowerInput>
}

export type OrderFlowerUsageCreateManyFlowerInputEnvelope = {
  data: Prisma.OrderFlowerUsageCreateManyFlowerInput | Prisma.OrderFlowerUsageCreateManyFlowerInput[]
  skipDuplicates?: boolean
}

export type OrderFlowerUsageUpsertWithWhereUniqueWithoutFlowerInput = {
  where: Prisma.OrderFlowerUsageWhereUniqueInput
  update: Prisma.XOR<Prisma.OrderFlowerUsageUpdateWithoutFlowerInput, Prisma.OrderFlowerUsageUncheckedUpdateWithoutFlowerInput>
  create: Prisma.XOR<Prisma.OrderFlowerUsageCreateWithoutFlowerInput, Prisma.OrderFlowerUsageUncheckedCreateWithoutFlowerInput>
}

export type OrderFlowerUsageUpdateWithWhereUniqueWithoutFlowerInput = {
  where: Prisma.OrderFlowerUsageWhereUniqueInput
  data: Prisma.XOR<Prisma.OrderFlowerUsageUpdateWithoutFlowerInput, Prisma.OrderFlowerUsageUncheckedUpdateWithoutFlowerInput>
}

export type OrderFlowerUsageUpdateManyWithWhereWithoutFlowerInput = {
  where: Prisma.OrderFlowerUsageScalarWhereInput
  data: Prisma.XOR<Prisma.OrderFlowerUsageUpdateManyMutationInput, Prisma.OrderFlowerUsageUncheckedUpdateManyWithoutFlowerInput>
}

export type OrderFlowerUsageCreateManyOrderInput = {
  id?: string
  flowerId: string
  quantity: number
  unitType: $Enums.UnitType
  createdAt?: Date | string
}

export type OrderFlowerUsageUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  flower?: Prisma.FlowerUpdateOneRequiredWithoutUsagesNestedInput
}

export type OrderFlowerUsageUncheckedUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flowerId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrderFlowerUsageUncheckedUpdateManyWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flowerId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrderFlowerUsageCreateManyFlowerInput = {
  id?: string
  orderId: string
  quantity: number
  unitType: $Enums.UnitType
  createdAt?: Date | string
}

export type OrderFlowerUsageUpdateWithoutFlowerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.OrderUpdateOneRequiredWithoutFlowerUsagesNestedInput
}

export type OrderFlowerUsageUncheckedUpdateWithoutFlowerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrderFlowerUsageUncheckedUpdateManyWithoutFlowerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitType?: Prisma.EnumUnitTypeFieldUpdateOperationsInput | $Enums.UnitType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type OrderFlowerUsageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderId?: boolean
  flowerId?: boolean
  quantity?: boolean
  unitType?: boolean
  createdAt?: boolean
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
  flower?: boolean | Prisma.FlowerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["orderFlowerUsage"]>



export type OrderFlowerUsageSelectScalar = {
  id?: boolean
  orderId?: boolean
  flowerId?: boolean
  quantity?: boolean
  unitType?: boolean
  createdAt?: boolean
}

export type OrderFlowerUsageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "orderId" | "flowerId" | "quantity" | "unitType" | "createdAt", ExtArgs["result"]["orderFlowerUsage"]>
export type OrderFlowerUsageInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
  flower?: boolean | Prisma.FlowerDefaultArgs<ExtArgs>
}

export type $OrderFlowerUsagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "OrderFlowerUsage"
  objects: {
    order: Prisma.$OrderPayload<ExtArgs>
    flower: Prisma.$FlowerPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    orderId: string
    flowerId: string
    quantity: number
    unitType: $Enums.UnitType
    createdAt: Date
  }, ExtArgs["result"]["orderFlowerUsage"]>
  composites: {}
}

export type OrderFlowerUsageGetPayload<S extends boolean | null | undefined | OrderFlowerUsageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OrderFlowerUsagePayload, S>

export type OrderFlowerUsageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OrderFlowerUsageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OrderFlowerUsageCountAggregateInputType | true
  }

export interface OrderFlowerUsageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['OrderFlowerUsage'], meta: { name: 'OrderFlowerUsage' } }
  /**
   * Find zero or one OrderFlowerUsage that matches the filter.
   * @param {OrderFlowerUsageFindUniqueArgs} args - Arguments to find a OrderFlowerUsage
   * @example
   * // Get one OrderFlowerUsage
   * const orderFlowerUsage = await prisma.orderFlowerUsage.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OrderFlowerUsageFindUniqueArgs>(args: Prisma.SelectSubset<T, OrderFlowerUsageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OrderFlowerUsageClient<runtime.Types.Result.GetResult<Prisma.$OrderFlowerUsagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OrderFlowerUsage that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OrderFlowerUsageFindUniqueOrThrowArgs} args - Arguments to find a OrderFlowerUsage
   * @example
   * // Get one OrderFlowerUsage
   * const orderFlowerUsage = await prisma.orderFlowerUsage.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OrderFlowerUsageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OrderFlowerUsageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrderFlowerUsageClient<runtime.Types.Result.GetResult<Prisma.$OrderFlowerUsagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrderFlowerUsage that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderFlowerUsageFindFirstArgs} args - Arguments to find a OrderFlowerUsage
   * @example
   * // Get one OrderFlowerUsage
   * const orderFlowerUsage = await prisma.orderFlowerUsage.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OrderFlowerUsageFindFirstArgs>(args?: Prisma.SelectSubset<T, OrderFlowerUsageFindFirstArgs<ExtArgs>>): Prisma.Prisma__OrderFlowerUsageClient<runtime.Types.Result.GetResult<Prisma.$OrderFlowerUsagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrderFlowerUsage that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderFlowerUsageFindFirstOrThrowArgs} args - Arguments to find a OrderFlowerUsage
   * @example
   * // Get one OrderFlowerUsage
   * const orderFlowerUsage = await prisma.orderFlowerUsage.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OrderFlowerUsageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OrderFlowerUsageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrderFlowerUsageClient<runtime.Types.Result.GetResult<Prisma.$OrderFlowerUsagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OrderFlowerUsages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderFlowerUsageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OrderFlowerUsages
   * const orderFlowerUsages = await prisma.orderFlowerUsage.findMany()
   * 
   * // Get first 10 OrderFlowerUsages
   * const orderFlowerUsages = await prisma.orderFlowerUsage.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const orderFlowerUsageWithIdOnly = await prisma.orderFlowerUsage.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends OrderFlowerUsageFindManyArgs>(args?: Prisma.SelectSubset<T, OrderFlowerUsageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderFlowerUsagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OrderFlowerUsage.
   * @param {OrderFlowerUsageCreateArgs} args - Arguments to create a OrderFlowerUsage.
   * @example
   * // Create one OrderFlowerUsage
   * const OrderFlowerUsage = await prisma.orderFlowerUsage.create({
   *   data: {
   *     // ... data to create a OrderFlowerUsage
   *   }
   * })
   * 
   */
  create<T extends OrderFlowerUsageCreateArgs>(args: Prisma.SelectSubset<T, OrderFlowerUsageCreateArgs<ExtArgs>>): Prisma.Prisma__OrderFlowerUsageClient<runtime.Types.Result.GetResult<Prisma.$OrderFlowerUsagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OrderFlowerUsages.
   * @param {OrderFlowerUsageCreateManyArgs} args - Arguments to create many OrderFlowerUsages.
   * @example
   * // Create many OrderFlowerUsages
   * const orderFlowerUsage = await prisma.orderFlowerUsage.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends OrderFlowerUsageCreateManyArgs>(args?: Prisma.SelectSubset<T, OrderFlowerUsageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a OrderFlowerUsage.
   * @param {OrderFlowerUsageDeleteArgs} args - Arguments to delete one OrderFlowerUsage.
   * @example
   * // Delete one OrderFlowerUsage
   * const OrderFlowerUsage = await prisma.orderFlowerUsage.delete({
   *   where: {
   *     // ... filter to delete one OrderFlowerUsage
   *   }
   * })
   * 
   */
  delete<T extends OrderFlowerUsageDeleteArgs>(args: Prisma.SelectSubset<T, OrderFlowerUsageDeleteArgs<ExtArgs>>): Prisma.Prisma__OrderFlowerUsageClient<runtime.Types.Result.GetResult<Prisma.$OrderFlowerUsagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OrderFlowerUsage.
   * @param {OrderFlowerUsageUpdateArgs} args - Arguments to update one OrderFlowerUsage.
   * @example
   * // Update one OrderFlowerUsage
   * const orderFlowerUsage = await prisma.orderFlowerUsage.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends OrderFlowerUsageUpdateArgs>(args: Prisma.SelectSubset<T, OrderFlowerUsageUpdateArgs<ExtArgs>>): Prisma.Prisma__OrderFlowerUsageClient<runtime.Types.Result.GetResult<Prisma.$OrderFlowerUsagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OrderFlowerUsages.
   * @param {OrderFlowerUsageDeleteManyArgs} args - Arguments to filter OrderFlowerUsages to delete.
   * @example
   * // Delete a few OrderFlowerUsages
   * const { count } = await prisma.orderFlowerUsage.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends OrderFlowerUsageDeleteManyArgs>(args?: Prisma.SelectSubset<T, OrderFlowerUsageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OrderFlowerUsages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderFlowerUsageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OrderFlowerUsages
   * const orderFlowerUsage = await prisma.orderFlowerUsage.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends OrderFlowerUsageUpdateManyArgs>(args: Prisma.SelectSubset<T, OrderFlowerUsageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one OrderFlowerUsage.
   * @param {OrderFlowerUsageUpsertArgs} args - Arguments to update or create a OrderFlowerUsage.
   * @example
   * // Update or create a OrderFlowerUsage
   * const orderFlowerUsage = await prisma.orderFlowerUsage.upsert({
   *   create: {
   *     // ... data to create a OrderFlowerUsage
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OrderFlowerUsage we want to update
   *   }
   * })
   */
  upsert<T extends OrderFlowerUsageUpsertArgs>(args: Prisma.SelectSubset<T, OrderFlowerUsageUpsertArgs<ExtArgs>>): Prisma.Prisma__OrderFlowerUsageClient<runtime.Types.Result.GetResult<Prisma.$OrderFlowerUsagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OrderFlowerUsages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderFlowerUsageCountArgs} args - Arguments to filter OrderFlowerUsages to count.
   * @example
   * // Count the number of OrderFlowerUsages
   * const count = await prisma.orderFlowerUsage.count({
   *   where: {
   *     // ... the filter for the OrderFlowerUsages we want to count
   *   }
   * })
  **/
  count<T extends OrderFlowerUsageCountArgs>(
    args?: Prisma.Subset<T, OrderFlowerUsageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OrderFlowerUsageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OrderFlowerUsage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderFlowerUsageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OrderFlowerUsageAggregateArgs>(args: Prisma.Subset<T, OrderFlowerUsageAggregateArgs>): Prisma.PrismaPromise<GetOrderFlowerUsageAggregateType<T>>

  /**
   * Group by OrderFlowerUsage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderFlowerUsageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends OrderFlowerUsageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OrderFlowerUsageGroupByArgs['orderBy'] }
      : { orderBy?: OrderFlowerUsageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OrderFlowerUsageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOrderFlowerUsageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the OrderFlowerUsage model
 */
readonly fields: OrderFlowerUsageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OrderFlowerUsage.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OrderFlowerUsageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  order<T extends Prisma.OrderDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrderDefaultArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  flower<T extends Prisma.FlowerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FlowerDefaultArgs<ExtArgs>>): Prisma.Prisma__FlowerClient<runtime.Types.Result.GetResult<Prisma.$FlowerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the OrderFlowerUsage model
 */
export interface OrderFlowerUsageFieldRefs {
  readonly id: Prisma.FieldRef<"OrderFlowerUsage", 'String'>
  readonly orderId: Prisma.FieldRef<"OrderFlowerUsage", 'String'>
  readonly flowerId: Prisma.FieldRef<"OrderFlowerUsage", 'String'>
  readonly quantity: Prisma.FieldRef<"OrderFlowerUsage", 'Int'>
  readonly unitType: Prisma.FieldRef<"OrderFlowerUsage", 'UnitType'>
  readonly createdAt: Prisma.FieldRef<"OrderFlowerUsage", 'DateTime'>
}
    

// Custom InputTypes
/**
 * OrderFlowerUsage findUnique
 */
export type OrderFlowerUsageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderFlowerUsage
   */
  select?: Prisma.OrderFlowerUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderFlowerUsage
   */
  omit?: Prisma.OrderFlowerUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderFlowerUsageInclude<ExtArgs> | null
  /**
   * Filter, which OrderFlowerUsage to fetch.
   */
  where: Prisma.OrderFlowerUsageWhereUniqueInput
}

/**
 * OrderFlowerUsage findUniqueOrThrow
 */
export type OrderFlowerUsageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderFlowerUsage
   */
  select?: Prisma.OrderFlowerUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderFlowerUsage
   */
  omit?: Prisma.OrderFlowerUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderFlowerUsageInclude<ExtArgs> | null
  /**
   * Filter, which OrderFlowerUsage to fetch.
   */
  where: Prisma.OrderFlowerUsageWhereUniqueInput
}

/**
 * OrderFlowerUsage findFirst
 */
export type OrderFlowerUsageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderFlowerUsage
   */
  select?: Prisma.OrderFlowerUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderFlowerUsage
   */
  omit?: Prisma.OrderFlowerUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderFlowerUsageInclude<ExtArgs> | null
  /**
   * Filter, which OrderFlowerUsage to fetch.
   */
  where?: Prisma.OrderFlowerUsageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrderFlowerUsages to fetch.
   */
  orderBy?: Prisma.OrderFlowerUsageOrderByWithRelationInput | Prisma.OrderFlowerUsageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OrderFlowerUsages.
   */
  cursor?: Prisma.OrderFlowerUsageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrderFlowerUsages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrderFlowerUsages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrderFlowerUsages.
   */
  distinct?: Prisma.OrderFlowerUsageScalarFieldEnum | Prisma.OrderFlowerUsageScalarFieldEnum[]
}

/**
 * OrderFlowerUsage findFirstOrThrow
 */
export type OrderFlowerUsageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderFlowerUsage
   */
  select?: Prisma.OrderFlowerUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderFlowerUsage
   */
  omit?: Prisma.OrderFlowerUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderFlowerUsageInclude<ExtArgs> | null
  /**
   * Filter, which OrderFlowerUsage to fetch.
   */
  where?: Prisma.OrderFlowerUsageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrderFlowerUsages to fetch.
   */
  orderBy?: Prisma.OrderFlowerUsageOrderByWithRelationInput | Prisma.OrderFlowerUsageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OrderFlowerUsages.
   */
  cursor?: Prisma.OrderFlowerUsageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrderFlowerUsages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrderFlowerUsages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrderFlowerUsages.
   */
  distinct?: Prisma.OrderFlowerUsageScalarFieldEnum | Prisma.OrderFlowerUsageScalarFieldEnum[]
}

/**
 * OrderFlowerUsage findMany
 */
export type OrderFlowerUsageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderFlowerUsage
   */
  select?: Prisma.OrderFlowerUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderFlowerUsage
   */
  omit?: Prisma.OrderFlowerUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderFlowerUsageInclude<ExtArgs> | null
  /**
   * Filter, which OrderFlowerUsages to fetch.
   */
  where?: Prisma.OrderFlowerUsageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrderFlowerUsages to fetch.
   */
  orderBy?: Prisma.OrderFlowerUsageOrderByWithRelationInput | Prisma.OrderFlowerUsageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing OrderFlowerUsages.
   */
  cursor?: Prisma.OrderFlowerUsageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrderFlowerUsages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrderFlowerUsages.
   */
  skip?: number
  distinct?: Prisma.OrderFlowerUsageScalarFieldEnum | Prisma.OrderFlowerUsageScalarFieldEnum[]
}

/**
 * OrderFlowerUsage create
 */
export type OrderFlowerUsageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderFlowerUsage
   */
  select?: Prisma.OrderFlowerUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderFlowerUsage
   */
  omit?: Prisma.OrderFlowerUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderFlowerUsageInclude<ExtArgs> | null
  /**
   * The data needed to create a OrderFlowerUsage.
   */
  data: Prisma.XOR<Prisma.OrderFlowerUsageCreateInput, Prisma.OrderFlowerUsageUncheckedCreateInput>
}

/**
 * OrderFlowerUsage createMany
 */
export type OrderFlowerUsageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many OrderFlowerUsages.
   */
  data: Prisma.OrderFlowerUsageCreateManyInput | Prisma.OrderFlowerUsageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OrderFlowerUsage update
 */
export type OrderFlowerUsageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderFlowerUsage
   */
  select?: Prisma.OrderFlowerUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderFlowerUsage
   */
  omit?: Prisma.OrderFlowerUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderFlowerUsageInclude<ExtArgs> | null
  /**
   * The data needed to update a OrderFlowerUsage.
   */
  data: Prisma.XOR<Prisma.OrderFlowerUsageUpdateInput, Prisma.OrderFlowerUsageUncheckedUpdateInput>
  /**
   * Choose, which OrderFlowerUsage to update.
   */
  where: Prisma.OrderFlowerUsageWhereUniqueInput
}

/**
 * OrderFlowerUsage updateMany
 */
export type OrderFlowerUsageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update OrderFlowerUsages.
   */
  data: Prisma.XOR<Prisma.OrderFlowerUsageUpdateManyMutationInput, Prisma.OrderFlowerUsageUncheckedUpdateManyInput>
  /**
   * Filter which OrderFlowerUsages to update
   */
  where?: Prisma.OrderFlowerUsageWhereInput
  /**
   * Limit how many OrderFlowerUsages to update.
   */
  limit?: number
}

/**
 * OrderFlowerUsage upsert
 */
export type OrderFlowerUsageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderFlowerUsage
   */
  select?: Prisma.OrderFlowerUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderFlowerUsage
   */
  omit?: Prisma.OrderFlowerUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderFlowerUsageInclude<ExtArgs> | null
  /**
   * The filter to search for the OrderFlowerUsage to update in case it exists.
   */
  where: Prisma.OrderFlowerUsageWhereUniqueInput
  /**
   * In case the OrderFlowerUsage found by the `where` argument doesn't exist, create a new OrderFlowerUsage with this data.
   */
  create: Prisma.XOR<Prisma.OrderFlowerUsageCreateInput, Prisma.OrderFlowerUsageUncheckedCreateInput>
  /**
   * In case the OrderFlowerUsage was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OrderFlowerUsageUpdateInput, Prisma.OrderFlowerUsageUncheckedUpdateInput>
}

/**
 * OrderFlowerUsage delete
 */
export type OrderFlowerUsageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderFlowerUsage
   */
  select?: Prisma.OrderFlowerUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderFlowerUsage
   */
  omit?: Prisma.OrderFlowerUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderFlowerUsageInclude<ExtArgs> | null
  /**
   * Filter which OrderFlowerUsage to delete.
   */
  where: Prisma.OrderFlowerUsageWhereUniqueInput
}

/**
 * OrderFlowerUsage deleteMany
 */
export type OrderFlowerUsageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OrderFlowerUsages to delete
   */
  where?: Prisma.OrderFlowerUsageWhereInput
  /**
   * Limit how many OrderFlowerUsages to delete.
   */
  limit?: number
}

/**
 * OrderFlowerUsage without action
 */
export type OrderFlowerUsageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderFlowerUsage
   */
  select?: Prisma.OrderFlowerUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderFlowerUsage
   */
  omit?: Prisma.OrderFlowerUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderFlowerUsageInclude<ExtArgs> | null
}
