
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `StockEvent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model StockEvent
 * 
 */
export type StockEventModel = runtime.Types.Result.DefaultSelection<Prisma.$StockEventPayload>

export type AggregateStockEvent = {
  _count: StockEventCountAggregateOutputType | null
  _avg: StockEventAvgAggregateOutputType | null
  _sum: StockEventSumAggregateOutputType | null
  _min: StockEventMinAggregateOutputType | null
  _max: StockEventMaxAggregateOutputType | null
}

export type StockEventAvgAggregateOutputType = {
  delta: number | null
}

export type StockEventSumAggregateOutputType = {
  delta: number | null
}

export type StockEventMinAggregateOutputType = {
  id: string | null
  flowerId: string | null
  userId: string | null
  orderId: string | null
  delta: number | null
  reason: string | null
  createdAt: Date | null
}

export type StockEventMaxAggregateOutputType = {
  id: string | null
  flowerId: string | null
  userId: string | null
  orderId: string | null
  delta: number | null
  reason: string | null
  createdAt: Date | null
}

export type StockEventCountAggregateOutputType = {
  id: number
  flowerId: number
  userId: number
  orderId: number
  delta: number
  reason: number
  createdAt: number
  _all: number
}


export type StockEventAvgAggregateInputType = {
  delta?: true
}

export type StockEventSumAggregateInputType = {
  delta?: true
}

export type StockEventMinAggregateInputType = {
  id?: true
  flowerId?: true
  userId?: true
  orderId?: true
  delta?: true
  reason?: true
  createdAt?: true
}

export type StockEventMaxAggregateInputType = {
  id?: true
  flowerId?: true
  userId?: true
  orderId?: true
  delta?: true
  reason?: true
  createdAt?: true
}

export type StockEventCountAggregateInputType = {
  id?: true
  flowerId?: true
  userId?: true
  orderId?: true
  delta?: true
  reason?: true
  createdAt?: true
  _all?: true
}

export type StockEventAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StockEvent to aggregate.
   */
  where?: Prisma.StockEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StockEvents to fetch.
   */
  orderBy?: Prisma.StockEventOrderByWithRelationInput | Prisma.StockEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StockEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StockEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StockEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StockEvents
  **/
  _count?: true | StockEventCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: StockEventAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: StockEventSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StockEventMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StockEventMaxAggregateInputType
}

export type GetStockEventAggregateType<T extends StockEventAggregateArgs> = {
      [P in keyof T & keyof AggregateStockEvent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStockEvent[P]>
    : Prisma.GetScalarType<T[P], AggregateStockEvent[P]>
}




export type StockEventGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StockEventWhereInput
  orderBy?: Prisma.StockEventOrderByWithAggregationInput | Prisma.StockEventOrderByWithAggregationInput[]
  by: Prisma.StockEventScalarFieldEnum[] | Prisma.StockEventScalarFieldEnum
  having?: Prisma.StockEventScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StockEventCountAggregateInputType | true
  _avg?: StockEventAvgAggregateInputType
  _sum?: StockEventSumAggregateInputType
  _min?: StockEventMinAggregateInputType
  _max?: StockEventMaxAggregateInputType
}

export type StockEventGroupByOutputType = {
  id: string
  flowerId: string
  userId: string | null
  orderId: string | null
  delta: number
  reason: string
  createdAt: Date
  _count: StockEventCountAggregateOutputType | null
  _avg: StockEventAvgAggregateOutputType | null
  _sum: StockEventSumAggregateOutputType | null
  _min: StockEventMinAggregateOutputType | null
  _max: StockEventMaxAggregateOutputType | null
}

type GetStockEventGroupByPayload<T extends StockEventGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StockEventGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StockEventGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StockEventGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StockEventGroupByOutputType[P]>
      }
    >
  >



export type StockEventWhereInput = {
  AND?: Prisma.StockEventWhereInput | Prisma.StockEventWhereInput[]
  OR?: Prisma.StockEventWhereInput[]
  NOT?: Prisma.StockEventWhereInput | Prisma.StockEventWhereInput[]
  id?: Prisma.StringFilter<"StockEvent"> | string
  flowerId?: Prisma.StringFilter<"StockEvent"> | string
  userId?: Prisma.StringNullableFilter<"StockEvent"> | string | null
  orderId?: Prisma.StringNullableFilter<"StockEvent"> | string | null
  delta?: Prisma.IntFilter<"StockEvent"> | number
  reason?: Prisma.StringFilter<"StockEvent"> | string
  createdAt?: Prisma.DateTimeFilter<"StockEvent"> | Date | string
  flower?: Prisma.XOR<Prisma.FlowerScalarRelationFilter, Prisma.FlowerWhereInput>
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  order?: Prisma.XOR<Prisma.OrderNullableScalarRelationFilter, Prisma.OrderWhereInput> | null
}

export type StockEventOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  flowerId?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  orderId?: Prisma.SortOrderInput | Prisma.SortOrder
  delta?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  flower?: Prisma.FlowerOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
  order?: Prisma.OrderOrderByWithRelationInput
  _relevance?: Prisma.StockEventOrderByRelevanceInput
}

export type StockEventWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.StockEventWhereInput | Prisma.StockEventWhereInput[]
  OR?: Prisma.StockEventWhereInput[]
  NOT?: Prisma.StockEventWhereInput | Prisma.StockEventWhereInput[]
  flowerId?: Prisma.StringFilter<"StockEvent"> | string
  userId?: Prisma.StringNullableFilter<"StockEvent"> | string | null
  orderId?: Prisma.StringNullableFilter<"StockEvent"> | string | null
  delta?: Prisma.IntFilter<"StockEvent"> | number
  reason?: Prisma.StringFilter<"StockEvent"> | string
  createdAt?: Prisma.DateTimeFilter<"StockEvent"> | Date | string
  flower?: Prisma.XOR<Prisma.FlowerScalarRelationFilter, Prisma.FlowerWhereInput>
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  order?: Prisma.XOR<Prisma.OrderNullableScalarRelationFilter, Prisma.OrderWhereInput> | null
}, "id">

export type StockEventOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  flowerId?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  orderId?: Prisma.SortOrderInput | Prisma.SortOrder
  delta?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.StockEventCountOrderByAggregateInput
  _avg?: Prisma.StockEventAvgOrderByAggregateInput
  _max?: Prisma.StockEventMaxOrderByAggregateInput
  _min?: Prisma.StockEventMinOrderByAggregateInput
  _sum?: Prisma.StockEventSumOrderByAggregateInput
}

export type StockEventScalarWhereWithAggregatesInput = {
  AND?: Prisma.StockEventScalarWhereWithAggregatesInput | Prisma.StockEventScalarWhereWithAggregatesInput[]
  OR?: Prisma.StockEventScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StockEventScalarWhereWithAggregatesInput | Prisma.StockEventScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"StockEvent"> | string
  flowerId?: Prisma.StringWithAggregatesFilter<"StockEvent"> | string
  userId?: Prisma.StringNullableWithAggregatesFilter<"StockEvent"> | string | null
  orderId?: Prisma.StringNullableWithAggregatesFilter<"StockEvent"> | string | null
  delta?: Prisma.IntWithAggregatesFilter<"StockEvent"> | number
  reason?: Prisma.StringWithAggregatesFilter<"StockEvent"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"StockEvent"> | Date | string
}

export type StockEventCreateInput = {
  id?: string
  delta: number
  reason: string
  createdAt?: Date | string
  flower: Prisma.FlowerCreateNestedOneWithoutStockEventsInput
  user?: Prisma.UserCreateNestedOneWithoutStockEventsInput
  order?: Prisma.OrderCreateNestedOneWithoutStockEventsInput
}

export type StockEventUncheckedCreateInput = {
  id?: string
  flowerId: string
  userId?: string | null
  orderId?: string | null
  delta: number
  reason: string
  createdAt?: Date | string
}

export type StockEventUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  flower?: Prisma.FlowerUpdateOneRequiredWithoutStockEventsNestedInput
  user?: Prisma.UserUpdateOneWithoutStockEventsNestedInput
  order?: Prisma.OrderUpdateOneWithoutStockEventsNestedInput
}

export type StockEventUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flowerId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  orderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StockEventCreateManyInput = {
  id?: string
  flowerId: string
  userId?: string | null
  orderId?: string | null
  delta: number
  reason: string
  createdAt?: Date | string
}

export type StockEventUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StockEventUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flowerId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  orderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StockEventListRelationFilter = {
  every?: Prisma.StockEventWhereInput
  some?: Prisma.StockEventWhereInput
  none?: Prisma.StockEventWhereInput
}

export type StockEventOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StockEventOrderByRelevanceInput = {
  fields: Prisma.StockEventOrderByRelevanceFieldEnum | Prisma.StockEventOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type StockEventCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  flowerId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  delta?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type StockEventAvgOrderByAggregateInput = {
  delta?: Prisma.SortOrder
}

export type StockEventMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  flowerId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  delta?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type StockEventMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  flowerId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  delta?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type StockEventSumOrderByAggregateInput = {
  delta?: Prisma.SortOrder
}

export type StockEventCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.StockEventCreateWithoutUserInput, Prisma.StockEventUncheckedCreateWithoutUserInput> | Prisma.StockEventCreateWithoutUserInput[] | Prisma.StockEventUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StockEventCreateOrConnectWithoutUserInput | Prisma.StockEventCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.StockEventCreateManyUserInputEnvelope
  connect?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
}

export type StockEventUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.StockEventCreateWithoutUserInput, Prisma.StockEventUncheckedCreateWithoutUserInput> | Prisma.StockEventCreateWithoutUserInput[] | Prisma.StockEventUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StockEventCreateOrConnectWithoutUserInput | Prisma.StockEventCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.StockEventCreateManyUserInputEnvelope
  connect?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
}

export type StockEventUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.StockEventCreateWithoutUserInput, Prisma.StockEventUncheckedCreateWithoutUserInput> | Prisma.StockEventCreateWithoutUserInput[] | Prisma.StockEventUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StockEventCreateOrConnectWithoutUserInput | Prisma.StockEventCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.StockEventUpsertWithWhereUniqueWithoutUserInput | Prisma.StockEventUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.StockEventCreateManyUserInputEnvelope
  set?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  disconnect?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  delete?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  connect?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  update?: Prisma.StockEventUpdateWithWhereUniqueWithoutUserInput | Prisma.StockEventUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.StockEventUpdateManyWithWhereWithoutUserInput | Prisma.StockEventUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.StockEventScalarWhereInput | Prisma.StockEventScalarWhereInput[]
}

export type StockEventUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.StockEventCreateWithoutUserInput, Prisma.StockEventUncheckedCreateWithoutUserInput> | Prisma.StockEventCreateWithoutUserInput[] | Prisma.StockEventUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StockEventCreateOrConnectWithoutUserInput | Prisma.StockEventCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.StockEventUpsertWithWhereUniqueWithoutUserInput | Prisma.StockEventUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.StockEventCreateManyUserInputEnvelope
  set?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  disconnect?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  delete?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  connect?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  update?: Prisma.StockEventUpdateWithWhereUniqueWithoutUserInput | Prisma.StockEventUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.StockEventUpdateManyWithWhereWithoutUserInput | Prisma.StockEventUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.StockEventScalarWhereInput | Prisma.StockEventScalarWhereInput[]
}

export type StockEventCreateNestedManyWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.StockEventCreateWithoutOrderInput, Prisma.StockEventUncheckedCreateWithoutOrderInput> | Prisma.StockEventCreateWithoutOrderInput[] | Prisma.StockEventUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.StockEventCreateOrConnectWithoutOrderInput | Prisma.StockEventCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.StockEventCreateManyOrderInputEnvelope
  connect?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
}

export type StockEventUncheckedCreateNestedManyWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.StockEventCreateWithoutOrderInput, Prisma.StockEventUncheckedCreateWithoutOrderInput> | Prisma.StockEventCreateWithoutOrderInput[] | Prisma.StockEventUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.StockEventCreateOrConnectWithoutOrderInput | Prisma.StockEventCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.StockEventCreateManyOrderInputEnvelope
  connect?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
}

export type StockEventUpdateManyWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.StockEventCreateWithoutOrderInput, Prisma.StockEventUncheckedCreateWithoutOrderInput> | Prisma.StockEventCreateWithoutOrderInput[] | Prisma.StockEventUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.StockEventCreateOrConnectWithoutOrderInput | Prisma.StockEventCreateOrConnectWithoutOrderInput[]
  upsert?: Prisma.StockEventUpsertWithWhereUniqueWithoutOrderInput | Prisma.StockEventUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.StockEventCreateManyOrderInputEnvelope
  set?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  disconnect?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  delete?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  connect?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  update?: Prisma.StockEventUpdateWithWhereUniqueWithoutOrderInput | Prisma.StockEventUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?: Prisma.StockEventUpdateManyWithWhereWithoutOrderInput | Prisma.StockEventUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?: Prisma.StockEventScalarWhereInput | Prisma.StockEventScalarWhereInput[]
}

export type StockEventUncheckedUpdateManyWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.StockEventCreateWithoutOrderInput, Prisma.StockEventUncheckedCreateWithoutOrderInput> | Prisma.StockEventCreateWithoutOrderInput[] | Prisma.StockEventUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.StockEventCreateOrConnectWithoutOrderInput | Prisma.StockEventCreateOrConnectWithoutOrderInput[]
  upsert?: Prisma.StockEventUpsertWithWhereUniqueWithoutOrderInput | Prisma.StockEventUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.StockEventCreateManyOrderInputEnvelope
  set?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  disconnect?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  delete?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  connect?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  update?: Prisma.StockEventUpdateWithWhereUniqueWithoutOrderInput | Prisma.StockEventUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?: Prisma.StockEventUpdateManyWithWhereWithoutOrderInput | Prisma.StockEventUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?: Prisma.StockEventScalarWhereInput | Prisma.StockEventScalarWhereInput[]
}

export type StockEventCreateNestedManyWithoutFlowerInput = {
  create?: Prisma.XOR<Prisma.StockEventCreateWithoutFlowerInput, Prisma.StockEventUncheckedCreateWithoutFlowerInput> | Prisma.StockEventCreateWithoutFlowerInput[] | Prisma.StockEventUncheckedCreateWithoutFlowerInput[]
  connectOrCreate?: Prisma.StockEventCreateOrConnectWithoutFlowerInput | Prisma.StockEventCreateOrConnectWithoutFlowerInput[]
  createMany?: Prisma.StockEventCreateManyFlowerInputEnvelope
  connect?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
}

export type StockEventUncheckedCreateNestedManyWithoutFlowerInput = {
  create?: Prisma.XOR<Prisma.StockEventCreateWithoutFlowerInput, Prisma.StockEventUncheckedCreateWithoutFlowerInput> | Prisma.StockEventCreateWithoutFlowerInput[] | Prisma.StockEventUncheckedCreateWithoutFlowerInput[]
  connectOrCreate?: Prisma.StockEventCreateOrConnectWithoutFlowerInput | Prisma.StockEventCreateOrConnectWithoutFlowerInput[]
  createMany?: Prisma.StockEventCreateManyFlowerInputEnvelope
  connect?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
}

export type StockEventUpdateManyWithoutFlowerNestedInput = {
  create?: Prisma.XOR<Prisma.StockEventCreateWithoutFlowerInput, Prisma.StockEventUncheckedCreateWithoutFlowerInput> | Prisma.StockEventCreateWithoutFlowerInput[] | Prisma.StockEventUncheckedCreateWithoutFlowerInput[]
  connectOrCreate?: Prisma.StockEventCreateOrConnectWithoutFlowerInput | Prisma.StockEventCreateOrConnectWithoutFlowerInput[]
  upsert?: Prisma.StockEventUpsertWithWhereUniqueWithoutFlowerInput | Prisma.StockEventUpsertWithWhereUniqueWithoutFlowerInput[]
  createMany?: Prisma.StockEventCreateManyFlowerInputEnvelope
  set?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  disconnect?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  delete?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  connect?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  update?: Prisma.StockEventUpdateWithWhereUniqueWithoutFlowerInput | Prisma.StockEventUpdateWithWhereUniqueWithoutFlowerInput[]
  updateMany?: Prisma.StockEventUpdateManyWithWhereWithoutFlowerInput | Prisma.StockEventUpdateManyWithWhereWithoutFlowerInput[]
  deleteMany?: Prisma.StockEventScalarWhereInput | Prisma.StockEventScalarWhereInput[]
}

export type StockEventUncheckedUpdateManyWithoutFlowerNestedInput = {
  create?: Prisma.XOR<Prisma.StockEventCreateWithoutFlowerInput, Prisma.StockEventUncheckedCreateWithoutFlowerInput> | Prisma.StockEventCreateWithoutFlowerInput[] | Prisma.StockEventUncheckedCreateWithoutFlowerInput[]
  connectOrCreate?: Prisma.StockEventCreateOrConnectWithoutFlowerInput | Prisma.StockEventCreateOrConnectWithoutFlowerInput[]
  upsert?: Prisma.StockEventUpsertWithWhereUniqueWithoutFlowerInput | Prisma.StockEventUpsertWithWhereUniqueWithoutFlowerInput[]
  createMany?: Prisma.StockEventCreateManyFlowerInputEnvelope
  set?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  disconnect?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  delete?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  connect?: Prisma.StockEventWhereUniqueInput | Prisma.StockEventWhereUniqueInput[]
  update?: Prisma.StockEventUpdateWithWhereUniqueWithoutFlowerInput | Prisma.StockEventUpdateWithWhereUniqueWithoutFlowerInput[]
  updateMany?: Prisma.StockEventUpdateManyWithWhereWithoutFlowerInput | Prisma.StockEventUpdateManyWithWhereWithoutFlowerInput[]
  deleteMany?: Prisma.StockEventScalarWhereInput | Prisma.StockEventScalarWhereInput[]
}

export type StockEventCreateWithoutUserInput = {
  id?: string
  delta: number
  reason: string
  createdAt?: Date | string
  flower: Prisma.FlowerCreateNestedOneWithoutStockEventsInput
  order?: Prisma.OrderCreateNestedOneWithoutStockEventsInput
}

export type StockEventUncheckedCreateWithoutUserInput = {
  id?: string
  flowerId: string
  orderId?: string | null
  delta: number
  reason: string
  createdAt?: Date | string
}

export type StockEventCreateOrConnectWithoutUserInput = {
  where: Prisma.StockEventWhereUniqueInput
  create: Prisma.XOR<Prisma.StockEventCreateWithoutUserInput, Prisma.StockEventUncheckedCreateWithoutUserInput>
}

export type StockEventCreateManyUserInputEnvelope = {
  data: Prisma.StockEventCreateManyUserInput | Prisma.StockEventCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type StockEventUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.StockEventWhereUniqueInput
  update: Prisma.XOR<Prisma.StockEventUpdateWithoutUserInput, Prisma.StockEventUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.StockEventCreateWithoutUserInput, Prisma.StockEventUncheckedCreateWithoutUserInput>
}

export type StockEventUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.StockEventWhereUniqueInput
  data: Prisma.XOR<Prisma.StockEventUpdateWithoutUserInput, Prisma.StockEventUncheckedUpdateWithoutUserInput>
}

export type StockEventUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.StockEventScalarWhereInput
  data: Prisma.XOR<Prisma.StockEventUpdateManyMutationInput, Prisma.StockEventUncheckedUpdateManyWithoutUserInput>
}

export type StockEventScalarWhereInput = {
  AND?: Prisma.StockEventScalarWhereInput | Prisma.StockEventScalarWhereInput[]
  OR?: Prisma.StockEventScalarWhereInput[]
  NOT?: Prisma.StockEventScalarWhereInput | Prisma.StockEventScalarWhereInput[]
  id?: Prisma.StringFilter<"StockEvent"> | string
  flowerId?: Prisma.StringFilter<"StockEvent"> | string
  userId?: Prisma.StringNullableFilter<"StockEvent"> | string | null
  orderId?: Prisma.StringNullableFilter<"StockEvent"> | string | null
  delta?: Prisma.IntFilter<"StockEvent"> | number
  reason?: Prisma.StringFilter<"StockEvent"> | string
  createdAt?: Prisma.DateTimeFilter<"StockEvent"> | Date | string
}

export type StockEventCreateWithoutOrderInput = {
  id?: string
  delta: number
  reason: string
  createdAt?: Date | string
  flower: Prisma.FlowerCreateNestedOneWithoutStockEventsInput
  user?: Prisma.UserCreateNestedOneWithoutStockEventsInput
}

export type StockEventUncheckedCreateWithoutOrderInput = {
  id?: string
  flowerId: string
  userId?: string | null
  delta: number
  reason: string
  createdAt?: Date | string
}

export type StockEventCreateOrConnectWithoutOrderInput = {
  where: Prisma.StockEventWhereUniqueInput
  create: Prisma.XOR<Prisma.StockEventCreateWithoutOrderInput, Prisma.StockEventUncheckedCreateWithoutOrderInput>
}

export type StockEventCreateManyOrderInputEnvelope = {
  data: Prisma.StockEventCreateManyOrderInput | Prisma.StockEventCreateManyOrderInput[]
  skipDuplicates?: boolean
}

export type StockEventUpsertWithWhereUniqueWithoutOrderInput = {
  where: Prisma.StockEventWhereUniqueInput
  update: Prisma.XOR<Prisma.StockEventUpdateWithoutOrderInput, Prisma.StockEventUncheckedUpdateWithoutOrderInput>
  create: Prisma.XOR<Prisma.StockEventCreateWithoutOrderInput, Prisma.StockEventUncheckedCreateWithoutOrderInput>
}

export type StockEventUpdateWithWhereUniqueWithoutOrderInput = {
  where: Prisma.StockEventWhereUniqueInput
  data: Prisma.XOR<Prisma.StockEventUpdateWithoutOrderInput, Prisma.StockEventUncheckedUpdateWithoutOrderInput>
}

export type StockEventUpdateManyWithWhereWithoutOrderInput = {
  where: Prisma.StockEventScalarWhereInput
  data: Prisma.XOR<Prisma.StockEventUpdateManyMutationInput, Prisma.StockEventUncheckedUpdateManyWithoutOrderInput>
}

export type StockEventCreateWithoutFlowerInput = {
  id?: string
  delta: number
  reason: string
  createdAt?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutStockEventsInput
  order?: Prisma.OrderCreateNestedOneWithoutStockEventsInput
}

export type StockEventUncheckedCreateWithoutFlowerInput = {
  id?: string
  userId?: string | null
  orderId?: string | null
  delta: number
  reason: string
  createdAt?: Date | string
}

export type StockEventCreateOrConnectWithoutFlowerInput = {
  where: Prisma.StockEventWhereUniqueInput
  create: Prisma.XOR<Prisma.StockEventCreateWithoutFlowerInput, Prisma.StockEventUncheckedCreateWithoutFlowerInput>
}

export type StockEventCreateManyFlowerInputEnvelope = {
  data: Prisma.StockEventCreateManyFlowerInput | Prisma.StockEventCreateManyFlowerInput[]
  skipDuplicates?: boolean
}

export type StockEventUpsertWithWhereUniqueWithoutFlowerInput = {
  where: Prisma.StockEventWhereUniqueInput
  update: Prisma.XOR<Prisma.StockEventUpdateWithoutFlowerInput, Prisma.StockEventUncheckedUpdateWithoutFlowerInput>
  create: Prisma.XOR<Prisma.StockEventCreateWithoutFlowerInput, Prisma.StockEventUncheckedCreateWithoutFlowerInput>
}

export type StockEventUpdateWithWhereUniqueWithoutFlowerInput = {
  where: Prisma.StockEventWhereUniqueInput
  data: Prisma.XOR<Prisma.StockEventUpdateWithoutFlowerInput, Prisma.StockEventUncheckedUpdateWithoutFlowerInput>
}

export type StockEventUpdateManyWithWhereWithoutFlowerInput = {
  where: Prisma.StockEventScalarWhereInput
  data: Prisma.XOR<Prisma.StockEventUpdateManyMutationInput, Prisma.StockEventUncheckedUpdateManyWithoutFlowerInput>
}

export type StockEventCreateManyUserInput = {
  id?: string
  flowerId: string
  orderId?: string | null
  delta: number
  reason: string
  createdAt?: Date | string
}

export type StockEventUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  flower?: Prisma.FlowerUpdateOneRequiredWithoutStockEventsNestedInput
  order?: Prisma.OrderUpdateOneWithoutStockEventsNestedInput
}

export type StockEventUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flowerId?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StockEventUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flowerId?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StockEventCreateManyOrderInput = {
  id?: string
  flowerId: string
  userId?: string | null
  delta: number
  reason: string
  createdAt?: Date | string
}

export type StockEventUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  flower?: Prisma.FlowerUpdateOneRequiredWithoutStockEventsNestedInput
  user?: Prisma.UserUpdateOneWithoutStockEventsNestedInput
}

export type StockEventUncheckedUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flowerId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StockEventUncheckedUpdateManyWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  flowerId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StockEventCreateManyFlowerInput = {
  id?: string
  userId?: string | null
  orderId?: string | null
  delta: number
  reason: string
  createdAt?: Date | string
}

export type StockEventUpdateWithoutFlowerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutStockEventsNestedInput
  order?: Prisma.OrderUpdateOneWithoutStockEventsNestedInput
}

export type StockEventUncheckedUpdateWithoutFlowerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  orderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StockEventUncheckedUpdateManyWithoutFlowerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  orderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type StockEventSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  flowerId?: boolean
  userId?: boolean
  orderId?: boolean
  delta?: boolean
  reason?: boolean
  createdAt?: boolean
  flower?: boolean | Prisma.FlowerDefaultArgs<ExtArgs>
  user?: boolean | Prisma.StockEvent$userArgs<ExtArgs>
  order?: boolean | Prisma.StockEvent$orderArgs<ExtArgs>
}, ExtArgs["result"]["stockEvent"]>



export type StockEventSelectScalar = {
  id?: boolean
  flowerId?: boolean
  userId?: boolean
  orderId?: boolean
  delta?: boolean
  reason?: boolean
  createdAt?: boolean
}

export type StockEventOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "flowerId" | "userId" | "orderId" | "delta" | "reason" | "createdAt", ExtArgs["result"]["stockEvent"]>
export type StockEventInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  flower?: boolean | Prisma.FlowerDefaultArgs<ExtArgs>
  user?: boolean | Prisma.StockEvent$userArgs<ExtArgs>
  order?: boolean | Prisma.StockEvent$orderArgs<ExtArgs>
}

export type $StockEventPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StockEvent"
  objects: {
    flower: Prisma.$FlowerPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs> | null
    order: Prisma.$OrderPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    flowerId: string
    userId: string | null
    orderId: string | null
    delta: number
    reason: string
    createdAt: Date
  }, ExtArgs["result"]["stockEvent"]>
  composites: {}
}

export type StockEventGetPayload<S extends boolean | null | undefined | StockEventDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StockEventPayload, S>

export type StockEventCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StockEventFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StockEventCountAggregateInputType | true
  }

export interface StockEventDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StockEvent'], meta: { name: 'StockEvent' } }
  /**
   * Find zero or one StockEvent that matches the filter.
   * @param {StockEventFindUniqueArgs} args - Arguments to find a StockEvent
   * @example
   * // Get one StockEvent
   * const stockEvent = await prisma.stockEvent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StockEventFindUniqueArgs>(args: Prisma.SelectSubset<T, StockEventFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StockEventClient<runtime.Types.Result.GetResult<Prisma.$StockEventPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StockEvent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StockEventFindUniqueOrThrowArgs} args - Arguments to find a StockEvent
   * @example
   * // Get one StockEvent
   * const stockEvent = await prisma.stockEvent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StockEventFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StockEventFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StockEventClient<runtime.Types.Result.GetResult<Prisma.$StockEventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StockEvent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StockEventFindFirstArgs} args - Arguments to find a StockEvent
   * @example
   * // Get one StockEvent
   * const stockEvent = await prisma.stockEvent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StockEventFindFirstArgs>(args?: Prisma.SelectSubset<T, StockEventFindFirstArgs<ExtArgs>>): Prisma.Prisma__StockEventClient<runtime.Types.Result.GetResult<Prisma.$StockEventPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StockEvent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StockEventFindFirstOrThrowArgs} args - Arguments to find a StockEvent
   * @example
   * // Get one StockEvent
   * const stockEvent = await prisma.stockEvent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StockEventFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StockEventFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StockEventClient<runtime.Types.Result.GetResult<Prisma.$StockEventPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StockEvents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StockEventFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StockEvents
   * const stockEvents = await prisma.stockEvent.findMany()
   * 
   * // Get first 10 StockEvents
   * const stockEvents = await prisma.stockEvent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const stockEventWithIdOnly = await prisma.stockEvent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StockEventFindManyArgs>(args?: Prisma.SelectSubset<T, StockEventFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StockEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StockEvent.
   * @param {StockEventCreateArgs} args - Arguments to create a StockEvent.
   * @example
   * // Create one StockEvent
   * const StockEvent = await prisma.stockEvent.create({
   *   data: {
   *     // ... data to create a StockEvent
   *   }
   * })
   * 
   */
  create<T extends StockEventCreateArgs>(args: Prisma.SelectSubset<T, StockEventCreateArgs<ExtArgs>>): Prisma.Prisma__StockEventClient<runtime.Types.Result.GetResult<Prisma.$StockEventPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StockEvents.
   * @param {StockEventCreateManyArgs} args - Arguments to create many StockEvents.
   * @example
   * // Create many StockEvents
   * const stockEvent = await prisma.stockEvent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StockEventCreateManyArgs>(args?: Prisma.SelectSubset<T, StockEventCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a StockEvent.
   * @param {StockEventDeleteArgs} args - Arguments to delete one StockEvent.
   * @example
   * // Delete one StockEvent
   * const StockEvent = await prisma.stockEvent.delete({
   *   where: {
   *     // ... filter to delete one StockEvent
   *   }
   * })
   * 
   */
  delete<T extends StockEventDeleteArgs>(args: Prisma.SelectSubset<T, StockEventDeleteArgs<ExtArgs>>): Prisma.Prisma__StockEventClient<runtime.Types.Result.GetResult<Prisma.$StockEventPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StockEvent.
   * @param {StockEventUpdateArgs} args - Arguments to update one StockEvent.
   * @example
   * // Update one StockEvent
   * const stockEvent = await prisma.stockEvent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StockEventUpdateArgs>(args: Prisma.SelectSubset<T, StockEventUpdateArgs<ExtArgs>>): Prisma.Prisma__StockEventClient<runtime.Types.Result.GetResult<Prisma.$StockEventPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StockEvents.
   * @param {StockEventDeleteManyArgs} args - Arguments to filter StockEvents to delete.
   * @example
   * // Delete a few StockEvents
   * const { count } = await prisma.stockEvent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StockEventDeleteManyArgs>(args?: Prisma.SelectSubset<T, StockEventDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StockEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StockEventUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StockEvents
   * const stockEvent = await prisma.stockEvent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StockEventUpdateManyArgs>(args: Prisma.SelectSubset<T, StockEventUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one StockEvent.
   * @param {StockEventUpsertArgs} args - Arguments to update or create a StockEvent.
   * @example
   * // Update or create a StockEvent
   * const stockEvent = await prisma.stockEvent.upsert({
   *   create: {
   *     // ... data to create a StockEvent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StockEvent we want to update
   *   }
   * })
   */
  upsert<T extends StockEventUpsertArgs>(args: Prisma.SelectSubset<T, StockEventUpsertArgs<ExtArgs>>): Prisma.Prisma__StockEventClient<runtime.Types.Result.GetResult<Prisma.$StockEventPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StockEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StockEventCountArgs} args - Arguments to filter StockEvents to count.
   * @example
   * // Count the number of StockEvents
   * const count = await prisma.stockEvent.count({
   *   where: {
   *     // ... the filter for the StockEvents we want to count
   *   }
   * })
  **/
  count<T extends StockEventCountArgs>(
    args?: Prisma.Subset<T, StockEventCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StockEventCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StockEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StockEventAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StockEventAggregateArgs>(args: Prisma.Subset<T, StockEventAggregateArgs>): Prisma.PrismaPromise<GetStockEventAggregateType<T>>

  /**
   * Group by StockEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StockEventGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StockEventGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StockEventGroupByArgs['orderBy'] }
      : { orderBy?: StockEventGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StockEventGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStockEventGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StockEvent model
 */
readonly fields: StockEventFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StockEvent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StockEventClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  flower<T extends Prisma.FlowerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FlowerDefaultArgs<ExtArgs>>): Prisma.Prisma__FlowerClient<runtime.Types.Result.GetResult<Prisma.$FlowerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.StockEvent$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StockEvent$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  order<T extends Prisma.StockEvent$orderArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StockEvent$orderArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StockEvent model
 */
export interface StockEventFieldRefs {
  readonly id: Prisma.FieldRef<"StockEvent", 'String'>
  readonly flowerId: Prisma.FieldRef<"StockEvent", 'String'>
  readonly userId: Prisma.FieldRef<"StockEvent", 'String'>
  readonly orderId: Prisma.FieldRef<"StockEvent", 'String'>
  readonly delta: Prisma.FieldRef<"StockEvent", 'Int'>
  readonly reason: Prisma.FieldRef<"StockEvent", 'String'>
  readonly createdAt: Prisma.FieldRef<"StockEvent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * StockEvent findUnique
 */
export type StockEventFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockEvent
   */
  select?: Prisma.StockEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockEvent
   */
  omit?: Prisma.StockEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockEventInclude<ExtArgs> | null
  /**
   * Filter, which StockEvent to fetch.
   */
  where: Prisma.StockEventWhereUniqueInput
}

/**
 * StockEvent findUniqueOrThrow
 */
export type StockEventFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockEvent
   */
  select?: Prisma.StockEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockEvent
   */
  omit?: Prisma.StockEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockEventInclude<ExtArgs> | null
  /**
   * Filter, which StockEvent to fetch.
   */
  where: Prisma.StockEventWhereUniqueInput
}

/**
 * StockEvent findFirst
 */
export type StockEventFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockEvent
   */
  select?: Prisma.StockEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockEvent
   */
  omit?: Prisma.StockEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockEventInclude<ExtArgs> | null
  /**
   * Filter, which StockEvent to fetch.
   */
  where?: Prisma.StockEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StockEvents to fetch.
   */
  orderBy?: Prisma.StockEventOrderByWithRelationInput | Prisma.StockEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StockEvents.
   */
  cursor?: Prisma.StockEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StockEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StockEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StockEvents.
   */
  distinct?: Prisma.StockEventScalarFieldEnum | Prisma.StockEventScalarFieldEnum[]
}

/**
 * StockEvent findFirstOrThrow
 */
export type StockEventFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockEvent
   */
  select?: Prisma.StockEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockEvent
   */
  omit?: Prisma.StockEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockEventInclude<ExtArgs> | null
  /**
   * Filter, which StockEvent to fetch.
   */
  where?: Prisma.StockEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StockEvents to fetch.
   */
  orderBy?: Prisma.StockEventOrderByWithRelationInput | Prisma.StockEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StockEvents.
   */
  cursor?: Prisma.StockEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StockEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StockEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StockEvents.
   */
  distinct?: Prisma.StockEventScalarFieldEnum | Prisma.StockEventScalarFieldEnum[]
}

/**
 * StockEvent findMany
 */
export type StockEventFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockEvent
   */
  select?: Prisma.StockEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockEvent
   */
  omit?: Prisma.StockEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockEventInclude<ExtArgs> | null
  /**
   * Filter, which StockEvents to fetch.
   */
  where?: Prisma.StockEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StockEvents to fetch.
   */
  orderBy?: Prisma.StockEventOrderByWithRelationInput | Prisma.StockEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StockEvents.
   */
  cursor?: Prisma.StockEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StockEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StockEvents.
   */
  skip?: number
  distinct?: Prisma.StockEventScalarFieldEnum | Prisma.StockEventScalarFieldEnum[]
}

/**
 * StockEvent create
 */
export type StockEventCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockEvent
   */
  select?: Prisma.StockEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockEvent
   */
  omit?: Prisma.StockEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockEventInclude<ExtArgs> | null
  /**
   * The data needed to create a StockEvent.
   */
  data: Prisma.XOR<Prisma.StockEventCreateInput, Prisma.StockEventUncheckedCreateInput>
}

/**
 * StockEvent createMany
 */
export type StockEventCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StockEvents.
   */
  data: Prisma.StockEventCreateManyInput | Prisma.StockEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StockEvent update
 */
export type StockEventUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockEvent
   */
  select?: Prisma.StockEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockEvent
   */
  omit?: Prisma.StockEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockEventInclude<ExtArgs> | null
  /**
   * The data needed to update a StockEvent.
   */
  data: Prisma.XOR<Prisma.StockEventUpdateInput, Prisma.StockEventUncheckedUpdateInput>
  /**
   * Choose, which StockEvent to update.
   */
  where: Prisma.StockEventWhereUniqueInput
}

/**
 * StockEvent updateMany
 */
export type StockEventUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StockEvents.
   */
  data: Prisma.XOR<Prisma.StockEventUpdateManyMutationInput, Prisma.StockEventUncheckedUpdateManyInput>
  /**
   * Filter which StockEvents to update
   */
  where?: Prisma.StockEventWhereInput
  /**
   * Limit how many StockEvents to update.
   */
  limit?: number
}

/**
 * StockEvent upsert
 */
export type StockEventUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockEvent
   */
  select?: Prisma.StockEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockEvent
   */
  omit?: Prisma.StockEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockEventInclude<ExtArgs> | null
  /**
   * The filter to search for the StockEvent to update in case it exists.
   */
  where: Prisma.StockEventWhereUniqueInput
  /**
   * In case the StockEvent found by the `where` argument doesn't exist, create a new StockEvent with this data.
   */
  create: Prisma.XOR<Prisma.StockEventCreateInput, Prisma.StockEventUncheckedCreateInput>
  /**
   * In case the StockEvent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StockEventUpdateInput, Prisma.StockEventUncheckedUpdateInput>
}

/**
 * StockEvent delete
 */
export type StockEventDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockEvent
   */
  select?: Prisma.StockEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockEvent
   */
  omit?: Prisma.StockEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockEventInclude<ExtArgs> | null
  /**
   * Filter which StockEvent to delete.
   */
  where: Prisma.StockEventWhereUniqueInput
}

/**
 * StockEvent deleteMany
 */
export type StockEventDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StockEvents to delete
   */
  where?: Prisma.StockEventWhereInput
  /**
   * Limit how many StockEvents to delete.
   */
  limit?: number
}

/**
 * StockEvent.user
 */
export type StockEvent$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * StockEvent.order
 */
export type StockEvent$orderArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  where?: Prisma.OrderWhereInput
}

/**
 * StockEvent without action
 */
export type StockEventDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockEvent
   */
  select?: Prisma.StockEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockEvent
   */
  omit?: Prisma.StockEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockEventInclude<ExtArgs> | null
}
