
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `User` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model User
 * 
 */
export type UserModel = runtime.Types.Result.DefaultSelection<Prisma.$UserPayload>

export type AggregateUser = {
  _count: UserCountAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

export type UserMinAggregateOutputType = {
  id: string | null
  username: string | null
  displayName: string | null
  passwordHash: string | null
  role: $Enums.Role | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserMaxAggregateOutputType = {
  id: string | null
  username: string | null
  displayName: string | null
  passwordHash: string | null
  role: $Enums.Role | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserCountAggregateOutputType = {
  id: number
  username: number
  displayName: number
  passwordHash: number
  role: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type UserMinAggregateInputType = {
  id?: true
  username?: true
  displayName?: true
  passwordHash?: true
  role?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type UserMaxAggregateInputType = {
  id?: true
  username?: true
  displayName?: true
  passwordHash?: true
  role?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type UserCountAggregateInputType = {
  id?: true
  username?: true
  displayName?: true
  passwordHash?: true
  role?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type UserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which User to aggregate.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Users
  **/
  _count?: true | UserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserMaxAggregateInputType
}

export type GetUserAggregateType<T extends UserAggregateArgs> = {
      [P in keyof T & keyof AggregateUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUser[P]>
    : Prisma.GetScalarType<T[P], AggregateUser[P]>
}




export type UserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithAggregationInput | Prisma.UserOrderByWithAggregationInput[]
  by: Prisma.UserScalarFieldEnum[] | Prisma.UserScalarFieldEnum
  having?: Prisma.UserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserCountAggregateInputType | true
  _min?: UserMinAggregateInputType
  _max?: UserMaxAggregateInputType
}

export type UserGroupByOutputType = {
  id: string
  username: string
  displayName: string
  passwordHash: string
  role: $Enums.Role
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  _count: UserCountAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

type GetUserGroupByPayload<T extends UserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
      }
    >
  >



export type UserWhereInput = {
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  id?: Prisma.StringFilter<"User"> | string
  username?: Prisma.StringFilter<"User"> | string
  displayName?: Prisma.StringFilter<"User"> | string
  passwordHash?: Prisma.StringFilter<"User"> | string
  role?: Prisma.EnumRoleFilter<"User"> | $Enums.Role
  isActive?: Prisma.BoolFilter<"User"> | boolean
  createdAt?: Prisma.DateTimeFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string
  createdOrders?: Prisma.OrderListRelationFilter
  assignedOrders?: Prisma.OrderListRelationFilter
  preparedOrders?: Prisma.OrderListRelationFilter
  orderEvents?: Prisma.OrderEventListRelationFilter
  stockEvents?: Prisma.StockEventListRelationFilter
  photosUploaded?: Prisma.OrderPhotoListRelationFilter
}

export type UserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  role?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdOrders?: Prisma.OrderOrderByRelationAggregateInput
  assignedOrders?: Prisma.OrderOrderByRelationAggregateInput
  preparedOrders?: Prisma.OrderOrderByRelationAggregateInput
  orderEvents?: Prisma.OrderEventOrderByRelationAggregateInput
  stockEvents?: Prisma.StockEventOrderByRelationAggregateInput
  photosUploaded?: Prisma.OrderPhotoOrderByRelationAggregateInput
  _relevance?: Prisma.UserOrderByRelevanceInput
}

export type UserWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  username?: string
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  displayName?: Prisma.StringFilter<"User"> | string
  passwordHash?: Prisma.StringFilter<"User"> | string
  role?: Prisma.EnumRoleFilter<"User"> | $Enums.Role
  isActive?: Prisma.BoolFilter<"User"> | boolean
  createdAt?: Prisma.DateTimeFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string
  createdOrders?: Prisma.OrderListRelationFilter
  assignedOrders?: Prisma.OrderListRelationFilter
  preparedOrders?: Prisma.OrderListRelationFilter
  orderEvents?: Prisma.OrderEventListRelationFilter
  stockEvents?: Prisma.StockEventListRelationFilter
  photosUploaded?: Prisma.OrderPhotoListRelationFilter
}, "id" | "username">

export type UserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  role?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.UserCountOrderByAggregateInput
  _max?: Prisma.UserMaxOrderByAggregateInput
  _min?: Prisma.UserMinOrderByAggregateInput
}

export type UserScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"User"> | string
  username?: Prisma.StringWithAggregatesFilter<"User"> | string
  displayName?: Prisma.StringWithAggregatesFilter<"User"> | string
  passwordHash?: Prisma.StringWithAggregatesFilter<"User"> | string
  role?: Prisma.EnumRoleWithAggregatesFilter<"User"> | $Enums.Role
  isActive?: Prisma.BoolWithAggregatesFilter<"User"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"User"> | Date | string
}

export type UserCreateInput = {
  id?: string
  username: string
  displayName: string
  passwordHash: string
  role: $Enums.Role
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdOrders?: Prisma.OrderCreateNestedManyWithoutCreatedByInput
  assignedOrders?: Prisma.OrderCreateNestedManyWithoutAssignedToInput
  preparedOrders?: Prisma.OrderCreateNestedManyWithoutPreparedByInput
  orderEvents?: Prisma.OrderEventCreateNestedManyWithoutUserInput
  stockEvents?: Prisma.StockEventCreateNestedManyWithoutUserInput
  photosUploaded?: Prisma.OrderPhotoCreateNestedManyWithoutUploaderInput
}

export type UserUncheckedCreateInput = {
  id?: string
  username: string
  displayName: string
  passwordHash: string
  role: $Enums.Role
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdOrders?: Prisma.OrderUncheckedCreateNestedManyWithoutCreatedByInput
  assignedOrders?: Prisma.OrderUncheckedCreateNestedManyWithoutAssignedToInput
  preparedOrders?: Prisma.OrderUncheckedCreateNestedManyWithoutPreparedByInput
  orderEvents?: Prisma.OrderEventUncheckedCreateNestedManyWithoutUserInput
  stockEvents?: Prisma.StockEventUncheckedCreateNestedManyWithoutUserInput
  photosUploaded?: Prisma.OrderPhotoUncheckedCreateNestedManyWithoutUploaderInput
}

export type UserUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdOrders?: Prisma.OrderUpdateManyWithoutCreatedByNestedInput
  assignedOrders?: Prisma.OrderUpdateManyWithoutAssignedToNestedInput
  preparedOrders?: Prisma.OrderUpdateManyWithoutPreparedByNestedInput
  orderEvents?: Prisma.OrderEventUpdateManyWithoutUserNestedInput
  stockEvents?: Prisma.StockEventUpdateManyWithoutUserNestedInput
  photosUploaded?: Prisma.OrderPhotoUpdateManyWithoutUploaderNestedInput
}

export type UserUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdOrders?: Prisma.OrderUncheckedUpdateManyWithoutCreatedByNestedInput
  assignedOrders?: Prisma.OrderUncheckedUpdateManyWithoutAssignedToNestedInput
  preparedOrders?: Prisma.OrderUncheckedUpdateManyWithoutPreparedByNestedInput
  orderEvents?: Prisma.OrderEventUncheckedUpdateManyWithoutUserNestedInput
  stockEvents?: Prisma.StockEventUncheckedUpdateManyWithoutUserNestedInput
  photosUploaded?: Prisma.OrderPhotoUncheckedUpdateManyWithoutUploaderNestedInput
}

export type UserCreateManyInput = {
  id?: string
  username: string
  displayName: string
  passwordHash: string
  role: $Enums.Role
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserOrderByRelevanceInput = {
  fields: Prisma.UserOrderByRelevanceFieldEnum | Prisma.UserOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type UserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  role?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  role?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  role?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserScalarRelationFilter = {
  is?: Prisma.UserWhereInput
  isNot?: Prisma.UserWhereInput
}

export type UserNullableScalarRelationFilter = {
  is?: Prisma.UserWhereInput | null
  isNot?: Prisma.UserWhereInput | null
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type EnumRoleFieldUpdateOperationsInput = {
  set?: $Enums.Role
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type UserCreateNestedOneWithoutCreatedOrdersInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCreatedOrdersInput, Prisma.UserUncheckedCreateWithoutCreatedOrdersInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCreatedOrdersInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserCreateNestedOneWithoutAssignedOrdersInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutAssignedOrdersInput, Prisma.UserUncheckedCreateWithoutAssignedOrdersInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutAssignedOrdersInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserCreateNestedOneWithoutPreparedOrdersInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutPreparedOrdersInput, Prisma.UserUncheckedCreateWithoutPreparedOrdersInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutPreparedOrdersInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutCreatedOrdersNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCreatedOrdersInput, Prisma.UserUncheckedCreateWithoutCreatedOrdersInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCreatedOrdersInput
  upsert?: Prisma.UserUpsertWithoutCreatedOrdersInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutCreatedOrdersInput, Prisma.UserUpdateWithoutCreatedOrdersInput>, Prisma.UserUncheckedUpdateWithoutCreatedOrdersInput>
}

export type UserUpdateOneWithoutAssignedOrdersNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutAssignedOrdersInput, Prisma.UserUncheckedCreateWithoutAssignedOrdersInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutAssignedOrdersInput
  upsert?: Prisma.UserUpsertWithoutAssignedOrdersInput
  disconnect?: Prisma.UserWhereInput | boolean
  delete?: Prisma.UserWhereInput | boolean
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutAssignedOrdersInput, Prisma.UserUpdateWithoutAssignedOrdersInput>, Prisma.UserUncheckedUpdateWithoutAssignedOrdersInput>
}

export type UserUpdateOneWithoutPreparedOrdersNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutPreparedOrdersInput, Prisma.UserUncheckedCreateWithoutPreparedOrdersInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutPreparedOrdersInput
  upsert?: Prisma.UserUpsertWithoutPreparedOrdersInput
  disconnect?: Prisma.UserWhereInput | boolean
  delete?: Prisma.UserWhereInput | boolean
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutPreparedOrdersInput, Prisma.UserUpdateWithoutPreparedOrdersInput>, Prisma.UserUncheckedUpdateWithoutPreparedOrdersInput>
}

export type UserCreateNestedOneWithoutStockEventsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutStockEventsInput, Prisma.UserUncheckedCreateWithoutStockEventsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutStockEventsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneWithoutStockEventsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutStockEventsInput, Prisma.UserUncheckedCreateWithoutStockEventsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutStockEventsInput
  upsert?: Prisma.UserUpsertWithoutStockEventsInput
  disconnect?: Prisma.UserWhereInput | boolean
  delete?: Prisma.UserWhereInput | boolean
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutStockEventsInput, Prisma.UserUpdateWithoutStockEventsInput>, Prisma.UserUncheckedUpdateWithoutStockEventsInput>
}

export type UserCreateNestedOneWithoutPhotosUploadedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutPhotosUploadedInput, Prisma.UserUncheckedCreateWithoutPhotosUploadedInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutPhotosUploadedInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutPhotosUploadedNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutPhotosUploadedInput, Prisma.UserUncheckedCreateWithoutPhotosUploadedInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutPhotosUploadedInput
  upsert?: Prisma.UserUpsertWithoutPhotosUploadedInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutPhotosUploadedInput, Prisma.UserUpdateWithoutPhotosUploadedInput>, Prisma.UserUncheckedUpdateWithoutPhotosUploadedInput>
}

export type UserCreateNestedOneWithoutOrderEventsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutOrderEventsInput, Prisma.UserUncheckedCreateWithoutOrderEventsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutOrderEventsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneWithoutOrderEventsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutOrderEventsInput, Prisma.UserUncheckedCreateWithoutOrderEventsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutOrderEventsInput
  upsert?: Prisma.UserUpsertWithoutOrderEventsInput
  disconnect?: Prisma.UserWhereInput | boolean
  delete?: Prisma.UserWhereInput | boolean
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutOrderEventsInput, Prisma.UserUpdateWithoutOrderEventsInput>, Prisma.UserUncheckedUpdateWithoutOrderEventsInput>
}

export type UserCreateWithoutCreatedOrdersInput = {
  id?: string
  username: string
  displayName: string
  passwordHash: string
  role: $Enums.Role
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  assignedOrders?: Prisma.OrderCreateNestedManyWithoutAssignedToInput
  preparedOrders?: Prisma.OrderCreateNestedManyWithoutPreparedByInput
  orderEvents?: Prisma.OrderEventCreateNestedManyWithoutUserInput
  stockEvents?: Prisma.StockEventCreateNestedManyWithoutUserInput
  photosUploaded?: Prisma.OrderPhotoCreateNestedManyWithoutUploaderInput
}

export type UserUncheckedCreateWithoutCreatedOrdersInput = {
  id?: string
  username: string
  displayName: string
  passwordHash: string
  role: $Enums.Role
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  assignedOrders?: Prisma.OrderUncheckedCreateNestedManyWithoutAssignedToInput
  preparedOrders?: Prisma.OrderUncheckedCreateNestedManyWithoutPreparedByInput
  orderEvents?: Prisma.OrderEventUncheckedCreateNestedManyWithoutUserInput
  stockEvents?: Prisma.StockEventUncheckedCreateNestedManyWithoutUserInput
  photosUploaded?: Prisma.OrderPhotoUncheckedCreateNestedManyWithoutUploaderInput
}

export type UserCreateOrConnectWithoutCreatedOrdersInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutCreatedOrdersInput, Prisma.UserUncheckedCreateWithoutCreatedOrdersInput>
}

export type UserCreateWithoutAssignedOrdersInput = {
  id?: string
  username: string
  displayName: string
  passwordHash: string
  role: $Enums.Role
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdOrders?: Prisma.OrderCreateNestedManyWithoutCreatedByInput
  preparedOrders?: Prisma.OrderCreateNestedManyWithoutPreparedByInput
  orderEvents?: Prisma.OrderEventCreateNestedManyWithoutUserInput
  stockEvents?: Prisma.StockEventCreateNestedManyWithoutUserInput
  photosUploaded?: Prisma.OrderPhotoCreateNestedManyWithoutUploaderInput
}

export type UserUncheckedCreateWithoutAssignedOrdersInput = {
  id?: string
  username: string
  displayName: string
  passwordHash: string
  role: $Enums.Role
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdOrders?: Prisma.OrderUncheckedCreateNestedManyWithoutCreatedByInput
  preparedOrders?: Prisma.OrderUncheckedCreateNestedManyWithoutPreparedByInput
  orderEvents?: Prisma.OrderEventUncheckedCreateNestedManyWithoutUserInput
  stockEvents?: Prisma.StockEventUncheckedCreateNestedManyWithoutUserInput
  photosUploaded?: Prisma.OrderPhotoUncheckedCreateNestedManyWithoutUploaderInput
}

export type UserCreateOrConnectWithoutAssignedOrdersInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutAssignedOrdersInput, Prisma.UserUncheckedCreateWithoutAssignedOrdersInput>
}

export type UserCreateWithoutPreparedOrdersInput = {
  id?: string
  username: string
  displayName: string
  passwordHash: string
  role: $Enums.Role
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdOrders?: Prisma.OrderCreateNestedManyWithoutCreatedByInput
  assignedOrders?: Prisma.OrderCreateNestedManyWithoutAssignedToInput
  orderEvents?: Prisma.OrderEventCreateNestedManyWithoutUserInput
  stockEvents?: Prisma.StockEventCreateNestedManyWithoutUserInput
  photosUploaded?: Prisma.OrderPhotoCreateNestedManyWithoutUploaderInput
}

export type UserUncheckedCreateWithoutPreparedOrdersInput = {
  id?: string
  username: string
  displayName: string
  passwordHash: string
  role: $Enums.Role
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdOrders?: Prisma.OrderUncheckedCreateNestedManyWithoutCreatedByInput
  assignedOrders?: Prisma.OrderUncheckedCreateNestedManyWithoutAssignedToInput
  orderEvents?: Prisma.OrderEventUncheckedCreateNestedManyWithoutUserInput
  stockEvents?: Prisma.StockEventUncheckedCreateNestedManyWithoutUserInput
  photosUploaded?: Prisma.OrderPhotoUncheckedCreateNestedManyWithoutUploaderInput
}

export type UserCreateOrConnectWithoutPreparedOrdersInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutPreparedOrdersInput, Prisma.UserUncheckedCreateWithoutPreparedOrdersInput>
}

export type UserUpsertWithoutCreatedOrdersInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutCreatedOrdersInput, Prisma.UserUncheckedUpdateWithoutCreatedOrdersInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutCreatedOrdersInput, Prisma.UserUncheckedCreateWithoutCreatedOrdersInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutCreatedOrdersInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutCreatedOrdersInput, Prisma.UserUncheckedUpdateWithoutCreatedOrdersInput>
}

export type UserUpdateWithoutCreatedOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assignedOrders?: Prisma.OrderUpdateManyWithoutAssignedToNestedInput
  preparedOrders?: Prisma.OrderUpdateManyWithoutPreparedByNestedInput
  orderEvents?: Prisma.OrderEventUpdateManyWithoutUserNestedInput
  stockEvents?: Prisma.StockEventUpdateManyWithoutUserNestedInput
  photosUploaded?: Prisma.OrderPhotoUpdateManyWithoutUploaderNestedInput
}

export type UserUncheckedUpdateWithoutCreatedOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assignedOrders?: Prisma.OrderUncheckedUpdateManyWithoutAssignedToNestedInput
  preparedOrders?: Prisma.OrderUncheckedUpdateManyWithoutPreparedByNestedInput
  orderEvents?: Prisma.OrderEventUncheckedUpdateManyWithoutUserNestedInput
  stockEvents?: Prisma.StockEventUncheckedUpdateManyWithoutUserNestedInput
  photosUploaded?: Prisma.OrderPhotoUncheckedUpdateManyWithoutUploaderNestedInput
}

export type UserUpsertWithoutAssignedOrdersInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutAssignedOrdersInput, Prisma.UserUncheckedUpdateWithoutAssignedOrdersInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutAssignedOrdersInput, Prisma.UserUncheckedCreateWithoutAssignedOrdersInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutAssignedOrdersInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutAssignedOrdersInput, Prisma.UserUncheckedUpdateWithoutAssignedOrdersInput>
}

export type UserUpdateWithoutAssignedOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdOrders?: Prisma.OrderUpdateManyWithoutCreatedByNestedInput
  preparedOrders?: Prisma.OrderUpdateManyWithoutPreparedByNestedInput
  orderEvents?: Prisma.OrderEventUpdateManyWithoutUserNestedInput
  stockEvents?: Prisma.StockEventUpdateManyWithoutUserNestedInput
  photosUploaded?: Prisma.OrderPhotoUpdateManyWithoutUploaderNestedInput
}

export type UserUncheckedUpdateWithoutAssignedOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdOrders?: Prisma.OrderUncheckedUpdateManyWithoutCreatedByNestedInput
  preparedOrders?: Prisma.OrderUncheckedUpdateManyWithoutPreparedByNestedInput
  orderEvents?: Prisma.OrderEventUncheckedUpdateManyWithoutUserNestedInput
  stockEvents?: Prisma.StockEventUncheckedUpdateManyWithoutUserNestedInput
  photosUploaded?: Prisma.OrderPhotoUncheckedUpdateManyWithoutUploaderNestedInput
}

export type UserUpsertWithoutPreparedOrdersInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutPreparedOrdersInput, Prisma.UserUncheckedUpdateWithoutPreparedOrdersInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutPreparedOrdersInput, Prisma.UserUncheckedCreateWithoutPreparedOrdersInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutPreparedOrdersInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutPreparedOrdersInput, Prisma.UserUncheckedUpdateWithoutPreparedOrdersInput>
}

export type UserUpdateWithoutPreparedOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdOrders?: Prisma.OrderUpdateManyWithoutCreatedByNestedInput
  assignedOrders?: Prisma.OrderUpdateManyWithoutAssignedToNestedInput
  orderEvents?: Prisma.OrderEventUpdateManyWithoutUserNestedInput
  stockEvents?: Prisma.StockEventUpdateManyWithoutUserNestedInput
  photosUploaded?: Prisma.OrderPhotoUpdateManyWithoutUploaderNestedInput
}

export type UserUncheckedUpdateWithoutPreparedOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdOrders?: Prisma.OrderUncheckedUpdateManyWithoutCreatedByNestedInput
  assignedOrders?: Prisma.OrderUncheckedUpdateManyWithoutAssignedToNestedInput
  orderEvents?: Prisma.OrderEventUncheckedUpdateManyWithoutUserNestedInput
  stockEvents?: Prisma.StockEventUncheckedUpdateManyWithoutUserNestedInput
  photosUploaded?: Prisma.OrderPhotoUncheckedUpdateManyWithoutUploaderNestedInput
}

export type UserCreateWithoutStockEventsInput = {
  id?: string
  username: string
  displayName: string
  passwordHash: string
  role: $Enums.Role
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdOrders?: Prisma.OrderCreateNestedManyWithoutCreatedByInput
  assignedOrders?: Prisma.OrderCreateNestedManyWithoutAssignedToInput
  preparedOrders?: Prisma.OrderCreateNestedManyWithoutPreparedByInput
  orderEvents?: Prisma.OrderEventCreateNestedManyWithoutUserInput
  photosUploaded?: Prisma.OrderPhotoCreateNestedManyWithoutUploaderInput
}

export type UserUncheckedCreateWithoutStockEventsInput = {
  id?: string
  username: string
  displayName: string
  passwordHash: string
  role: $Enums.Role
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdOrders?: Prisma.OrderUncheckedCreateNestedManyWithoutCreatedByInput
  assignedOrders?: Prisma.OrderUncheckedCreateNestedManyWithoutAssignedToInput
  preparedOrders?: Prisma.OrderUncheckedCreateNestedManyWithoutPreparedByInput
  orderEvents?: Prisma.OrderEventUncheckedCreateNestedManyWithoutUserInput
  photosUploaded?: Prisma.OrderPhotoUncheckedCreateNestedManyWithoutUploaderInput
}

export type UserCreateOrConnectWithoutStockEventsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutStockEventsInput, Prisma.UserUncheckedCreateWithoutStockEventsInput>
}

export type UserUpsertWithoutStockEventsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutStockEventsInput, Prisma.UserUncheckedUpdateWithoutStockEventsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutStockEventsInput, Prisma.UserUncheckedCreateWithoutStockEventsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutStockEventsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutStockEventsInput, Prisma.UserUncheckedUpdateWithoutStockEventsInput>
}

export type UserUpdateWithoutStockEventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdOrders?: Prisma.OrderUpdateManyWithoutCreatedByNestedInput
  assignedOrders?: Prisma.OrderUpdateManyWithoutAssignedToNestedInput
  preparedOrders?: Prisma.OrderUpdateManyWithoutPreparedByNestedInput
  orderEvents?: Prisma.OrderEventUpdateManyWithoutUserNestedInput
  photosUploaded?: Prisma.OrderPhotoUpdateManyWithoutUploaderNestedInput
}

export type UserUncheckedUpdateWithoutStockEventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdOrders?: Prisma.OrderUncheckedUpdateManyWithoutCreatedByNestedInput
  assignedOrders?: Prisma.OrderUncheckedUpdateManyWithoutAssignedToNestedInput
  preparedOrders?: Prisma.OrderUncheckedUpdateManyWithoutPreparedByNestedInput
  orderEvents?: Prisma.OrderEventUncheckedUpdateManyWithoutUserNestedInput
  photosUploaded?: Prisma.OrderPhotoUncheckedUpdateManyWithoutUploaderNestedInput
}

export type UserCreateWithoutPhotosUploadedInput = {
  id?: string
  username: string
  displayName: string
  passwordHash: string
  role: $Enums.Role
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdOrders?: Prisma.OrderCreateNestedManyWithoutCreatedByInput
  assignedOrders?: Prisma.OrderCreateNestedManyWithoutAssignedToInput
  preparedOrders?: Prisma.OrderCreateNestedManyWithoutPreparedByInput
  orderEvents?: Prisma.OrderEventCreateNestedManyWithoutUserInput
  stockEvents?: Prisma.StockEventCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutPhotosUploadedInput = {
  id?: string
  username: string
  displayName: string
  passwordHash: string
  role: $Enums.Role
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdOrders?: Prisma.OrderUncheckedCreateNestedManyWithoutCreatedByInput
  assignedOrders?: Prisma.OrderUncheckedCreateNestedManyWithoutAssignedToInput
  preparedOrders?: Prisma.OrderUncheckedCreateNestedManyWithoutPreparedByInput
  orderEvents?: Prisma.OrderEventUncheckedCreateNestedManyWithoutUserInput
  stockEvents?: Prisma.StockEventUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutPhotosUploadedInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutPhotosUploadedInput, Prisma.UserUncheckedCreateWithoutPhotosUploadedInput>
}

export type UserUpsertWithoutPhotosUploadedInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutPhotosUploadedInput, Prisma.UserUncheckedUpdateWithoutPhotosUploadedInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutPhotosUploadedInput, Prisma.UserUncheckedCreateWithoutPhotosUploadedInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutPhotosUploadedInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutPhotosUploadedInput, Prisma.UserUncheckedUpdateWithoutPhotosUploadedInput>
}

export type UserUpdateWithoutPhotosUploadedInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdOrders?: Prisma.OrderUpdateManyWithoutCreatedByNestedInput
  assignedOrders?: Prisma.OrderUpdateManyWithoutAssignedToNestedInput
  preparedOrders?: Prisma.OrderUpdateManyWithoutPreparedByNestedInput
  orderEvents?: Prisma.OrderEventUpdateManyWithoutUserNestedInput
  stockEvents?: Prisma.StockEventUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutPhotosUploadedInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdOrders?: Prisma.OrderUncheckedUpdateManyWithoutCreatedByNestedInput
  assignedOrders?: Prisma.OrderUncheckedUpdateManyWithoutAssignedToNestedInput
  preparedOrders?: Prisma.OrderUncheckedUpdateManyWithoutPreparedByNestedInput
  orderEvents?: Prisma.OrderEventUncheckedUpdateManyWithoutUserNestedInput
  stockEvents?: Prisma.StockEventUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutOrderEventsInput = {
  id?: string
  username: string
  displayName: string
  passwordHash: string
  role: $Enums.Role
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdOrders?: Prisma.OrderCreateNestedManyWithoutCreatedByInput
  assignedOrders?: Prisma.OrderCreateNestedManyWithoutAssignedToInput
  preparedOrders?: Prisma.OrderCreateNestedManyWithoutPreparedByInput
  stockEvents?: Prisma.StockEventCreateNestedManyWithoutUserInput
  photosUploaded?: Prisma.OrderPhotoCreateNestedManyWithoutUploaderInput
}

export type UserUncheckedCreateWithoutOrderEventsInput = {
  id?: string
  username: string
  displayName: string
  passwordHash: string
  role: $Enums.Role
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdOrders?: Prisma.OrderUncheckedCreateNestedManyWithoutCreatedByInput
  assignedOrders?: Prisma.OrderUncheckedCreateNestedManyWithoutAssignedToInput
  preparedOrders?: Prisma.OrderUncheckedCreateNestedManyWithoutPreparedByInput
  stockEvents?: Prisma.StockEventUncheckedCreateNestedManyWithoutUserInput
  photosUploaded?: Prisma.OrderPhotoUncheckedCreateNestedManyWithoutUploaderInput
}

export type UserCreateOrConnectWithoutOrderEventsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutOrderEventsInput, Prisma.UserUncheckedCreateWithoutOrderEventsInput>
}

export type UserUpsertWithoutOrderEventsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutOrderEventsInput, Prisma.UserUncheckedUpdateWithoutOrderEventsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutOrderEventsInput, Prisma.UserUncheckedCreateWithoutOrderEventsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutOrderEventsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutOrderEventsInput, Prisma.UserUncheckedUpdateWithoutOrderEventsInput>
}

export type UserUpdateWithoutOrderEventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdOrders?: Prisma.OrderUpdateManyWithoutCreatedByNestedInput
  assignedOrders?: Prisma.OrderUpdateManyWithoutAssignedToNestedInput
  preparedOrders?: Prisma.OrderUpdateManyWithoutPreparedByNestedInput
  stockEvents?: Prisma.StockEventUpdateManyWithoutUserNestedInput
  photosUploaded?: Prisma.OrderPhotoUpdateManyWithoutUploaderNestedInput
}

export type UserUncheckedUpdateWithoutOrderEventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdOrders?: Prisma.OrderUncheckedUpdateManyWithoutCreatedByNestedInput
  assignedOrders?: Prisma.OrderUncheckedUpdateManyWithoutAssignedToNestedInput
  preparedOrders?: Prisma.OrderUncheckedUpdateManyWithoutPreparedByNestedInput
  stockEvents?: Prisma.StockEventUncheckedUpdateManyWithoutUserNestedInput
  photosUploaded?: Prisma.OrderPhotoUncheckedUpdateManyWithoutUploaderNestedInput
}


/**
 * Count Type UserCountOutputType
 */

export type UserCountOutputType = {
  createdOrders: number
  assignedOrders: number
  preparedOrders: number
  orderEvents: number
  stockEvents: number
  photosUploaded: number
}

export type UserCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  createdOrders?: boolean | UserCountOutputTypeCountCreatedOrdersArgs
  assignedOrders?: boolean | UserCountOutputTypeCountAssignedOrdersArgs
  preparedOrders?: boolean | UserCountOutputTypeCountPreparedOrdersArgs
  orderEvents?: boolean | UserCountOutputTypeCountOrderEventsArgs
  stockEvents?: boolean | UserCountOutputTypeCountStockEventsArgs
  photosUploaded?: boolean | UserCountOutputTypeCountPhotosUploadedArgs
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCountOutputType
   */
  select?: Prisma.UserCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountCreatedOrdersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountAssignedOrdersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountPreparedOrdersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountOrderEventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderEventWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountStockEventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StockEventWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountPhotosUploadedArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderPhotoWhereInput
}


export type UserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  username?: boolean
  displayName?: boolean
  passwordHash?: boolean
  role?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  createdOrders?: boolean | Prisma.User$createdOrdersArgs<ExtArgs>
  assignedOrders?: boolean | Prisma.User$assignedOrdersArgs<ExtArgs>
  preparedOrders?: boolean | Prisma.User$preparedOrdersArgs<ExtArgs>
  orderEvents?: boolean | Prisma.User$orderEventsArgs<ExtArgs>
  stockEvents?: boolean | Prisma.User$stockEventsArgs<ExtArgs>
  photosUploaded?: boolean | Prisma.User$photosUploadedArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user"]>



export type UserSelectScalar = {
  id?: boolean
  username?: boolean
  displayName?: boolean
  passwordHash?: boolean
  role?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type UserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "username" | "displayName" | "passwordHash" | "role" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["user"]>
export type UserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  createdOrders?: boolean | Prisma.User$createdOrdersArgs<ExtArgs>
  assignedOrders?: boolean | Prisma.User$assignedOrdersArgs<ExtArgs>
  preparedOrders?: boolean | Prisma.User$preparedOrdersArgs<ExtArgs>
  orderEvents?: boolean | Prisma.User$orderEventsArgs<ExtArgs>
  stockEvents?: boolean | Prisma.User$stockEventsArgs<ExtArgs>
  photosUploaded?: boolean | Prisma.User$photosUploadedArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}

export type $UserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "User"
  objects: {
    createdOrders: Prisma.$OrderPayload<ExtArgs>[]
    assignedOrders: Prisma.$OrderPayload<ExtArgs>[]
    preparedOrders: Prisma.$OrderPayload<ExtArgs>[]
    orderEvents: Prisma.$OrderEventPayload<ExtArgs>[]
    stockEvents: Prisma.$StockEventPayload<ExtArgs>[]
    photosUploaded: Prisma.$OrderPhotoPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    username: string
    displayName: string
    passwordHash: string
    role: $Enums.Role
    isActive: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["user"]>
  composites: {}
}

export type UserGetPayload<S extends boolean | null | undefined | UserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserPayload, S>

export type UserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserCountAggregateInputType | true
  }

export interface UserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['User'], meta: { name: 'User' } }
  /**
   * Find zero or one User that matches the filter.
   * @param {UserFindUniqueArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserFindUniqueArgs>(args: Prisma.SelectSubset<T, UserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one User that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserFindUniqueOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserFindFirstArgs>(args?: Prisma.SelectSubset<T, UserFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Users
   * const users = await prisma.user.findMany()
   * 
   * // Get first 10 Users
   * const users = await prisma.user.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userWithIdOnly = await prisma.user.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserFindManyArgs>(args?: Prisma.SelectSubset<T, UserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a User.
   * @param {UserCreateArgs} args - Arguments to create a User.
   * @example
   * // Create one User
   * const User = await prisma.user.create({
   *   data: {
   *     // ... data to create a User
   *   }
   * })
   * 
   */
  create<T extends UserCreateArgs>(args: Prisma.SelectSubset<T, UserCreateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Users.
   * @param {UserCreateManyArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserCreateManyArgs>(args?: Prisma.SelectSubset<T, UserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a User.
   * @param {UserDeleteArgs} args - Arguments to delete one User.
   * @example
   * // Delete one User
   * const User = await prisma.user.delete({
   *   where: {
   *     // ... filter to delete one User
   *   }
   * })
   * 
   */
  delete<T extends UserDeleteArgs>(args: Prisma.SelectSubset<T, UserDeleteArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one User.
   * @param {UserUpdateArgs} args - Arguments to update one User.
   * @example
   * // Update one User
   * const user = await prisma.user.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserUpdateArgs>(args: Prisma.SelectSubset<T, UserUpdateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Users.
   * @param {UserDeleteManyArgs} args - Arguments to filter Users to delete.
   * @example
   * // Delete a few Users
   * const { count } = await prisma.user.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserUpdateManyArgs>(args: Prisma.SelectSubset<T, UserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one User.
   * @param {UserUpsertArgs} args - Arguments to update or create a User.
   * @example
   * // Update or create a User
   * const user = await prisma.user.upsert({
   *   create: {
   *     // ... data to create a User
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the User we want to update
   *   }
   * })
   */
  upsert<T extends UserUpsertArgs>(args: Prisma.SelectSubset<T, UserUpsertArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCountArgs} args - Arguments to filter Users to count.
   * @example
   * // Count the number of Users
   * const count = await prisma.user.count({
   *   where: {
   *     // ... the filter for the Users we want to count
   *   }
   * })
  **/
  count<T extends UserCountArgs>(
    args?: Prisma.Subset<T, UserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserAggregateArgs>(args: Prisma.Subset<T, UserAggregateArgs>): Prisma.PrismaPromise<GetUserAggregateType<T>>

  /**
   * Group by User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserGroupByArgs['orderBy'] }
      : { orderBy?: UserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the User model
 */
readonly fields: UserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for User.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  createdOrders<T extends Prisma.User$createdOrdersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$createdOrdersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  assignedOrders<T extends Prisma.User$assignedOrdersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$assignedOrdersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  preparedOrders<T extends Prisma.User$preparedOrdersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$preparedOrdersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  orderEvents<T extends Prisma.User$orderEventsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$orderEventsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  stockEvents<T extends Prisma.User$stockEventsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$stockEventsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StockEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  photosUploaded<T extends Prisma.User$photosUploadedArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$photosUploadedArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderPhotoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the User model
 */
export interface UserFieldRefs {
  readonly id: Prisma.FieldRef<"User", 'String'>
  readonly username: Prisma.FieldRef<"User", 'String'>
  readonly displayName: Prisma.FieldRef<"User", 'String'>
  readonly passwordHash: Prisma.FieldRef<"User", 'String'>
  readonly role: Prisma.FieldRef<"User", 'Role'>
  readonly isActive: Prisma.FieldRef<"User", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"User", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"User", 'DateTime'>
}
    

// Custom InputTypes
/**
 * User findUnique
 */
export type UserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findUniqueOrThrow
 */
export type UserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findFirst
 */
export type UserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findFirstOrThrow
 */
export type UserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findMany
 */
export type UserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User create
 */
export type UserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to create a User.
   */
  data: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
}

/**
 * User createMany
 */
export type UserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * User update
 */
export type UserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to update a User.
   */
  data: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
  /**
   * Choose, which User to update.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User updateMany
 */
export type UserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User upsert
 */
export type UserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The filter to search for the User to update in case it exists.
   */
  where: Prisma.UserWhereUniqueInput
  /**
   * In case the User found by the `where` argument doesn't exist, create a new User with this data.
   */
  create: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
  /**
   * In case the User was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
}

/**
 * User delete
 */
export type UserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter which User to delete.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User deleteMany
 */
export type UserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Users to delete
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to delete.
   */
  limit?: number
}

/**
 * User.createdOrders
 */
export type User$createdOrdersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  where?: Prisma.OrderWhereInput
  orderBy?: Prisma.OrderOrderByWithRelationInput | Prisma.OrderOrderByWithRelationInput[]
  cursor?: Prisma.OrderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrderScalarFieldEnum | Prisma.OrderScalarFieldEnum[]
}

/**
 * User.assignedOrders
 */
export type User$assignedOrdersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  where?: Prisma.OrderWhereInput
  orderBy?: Prisma.OrderOrderByWithRelationInput | Prisma.OrderOrderByWithRelationInput[]
  cursor?: Prisma.OrderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrderScalarFieldEnum | Prisma.OrderScalarFieldEnum[]
}

/**
 * User.preparedOrders
 */
export type User$preparedOrdersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  where?: Prisma.OrderWhereInput
  orderBy?: Prisma.OrderOrderByWithRelationInput | Prisma.OrderOrderByWithRelationInput[]
  cursor?: Prisma.OrderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrderScalarFieldEnum | Prisma.OrderScalarFieldEnum[]
}

/**
 * User.orderEvents
 */
export type User$orderEventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderEvent
   */
  select?: Prisma.OrderEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderEvent
   */
  omit?: Prisma.OrderEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderEventInclude<ExtArgs> | null
  where?: Prisma.OrderEventWhereInput
  orderBy?: Prisma.OrderEventOrderByWithRelationInput | Prisma.OrderEventOrderByWithRelationInput[]
  cursor?: Prisma.OrderEventWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrderEventScalarFieldEnum | Prisma.OrderEventScalarFieldEnum[]
}

/**
 * User.stockEvents
 */
export type User$stockEventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockEvent
   */
  select?: Prisma.StockEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockEvent
   */
  omit?: Prisma.StockEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockEventInclude<ExtArgs> | null
  where?: Prisma.StockEventWhereInput
  orderBy?: Prisma.StockEventOrderByWithRelationInput | Prisma.StockEventOrderByWithRelationInput[]
  cursor?: Prisma.StockEventWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.StockEventScalarFieldEnum | Prisma.StockEventScalarFieldEnum[]
}

/**
 * User.photosUploaded
 */
export type User$photosUploadedArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrderPhoto
   */
  select?: Prisma.OrderPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrderPhoto
   */
  omit?: Prisma.OrderPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderPhotoInclude<ExtArgs> | null
  where?: Prisma.OrderPhotoWhereInput
  orderBy?: Prisma.OrderPhotoOrderByWithRelationInput | Prisma.OrderPhotoOrderByWithRelationInput[]
  cursor?: Prisma.OrderPhotoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrderPhotoScalarFieldEnum | Prisma.OrderPhotoScalarFieldEnum[]
}

/**
 * User without action
 */
export type UserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
}
