
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  User: 'User',
  Customer: 'Customer',
  Order: 'Order',
  Flower: 'Flower',
  OrderFlowerUsage: 'OrderFlowerUsage',
  StockEvent: 'StockEvent',
  OrderPhoto: 'OrderPhoto',
  OrderEvent: 'OrderEvent'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  displayName: 'displayName',
  passwordHash: 'passwordHash',
  role: 'role',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const CustomerScalarFieldEnum = {
  id: 'id',
  fullName: 'fullName',
  phone: 'phone',
  email: 'email',
  address: 'address',
  birthday: 'birthday',
  notes: 'notes',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CustomerScalarFieldEnum = (typeof CustomerScalarFieldEnum)[keyof typeof CustomerScalarFieldEnum]


export const OrderScalarFieldEnum = {
  id: 'id',
  customerFullName: 'customerFullName',
  customerPhone: 'customerPhone',
  deliveryDate: 'deliveryDate',
  deliveryTime: 'deliveryTime',
  orderType: 'orderType',
  deliveryAddress: 'deliveryAddress',
  notes: 'notes',
  amount: 'amount',
  status: 'status',
  customerId: 'customerId',
  createdById: 'createdById',
  assignedToId: 'assignedToId',
  preparedById: 'preparedById',
  prepNotes: 'prepNotes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type OrderScalarFieldEnum = (typeof OrderScalarFieldEnum)[keyof typeof OrderScalarFieldEnum]


export const FlowerScalarFieldEnum = {
  id: 'id',
  name: 'name',
  unitType: 'unitType',
  stockQuantity: 'stockQuantity',
  lowStockLevel: 'lowStockLevel',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type FlowerScalarFieldEnum = (typeof FlowerScalarFieldEnum)[keyof typeof FlowerScalarFieldEnum]


export const OrderFlowerUsageScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  flowerId: 'flowerId',
  quantity: 'quantity',
  unitType: 'unitType',
  createdAt: 'createdAt'
} as const

export type OrderFlowerUsageScalarFieldEnum = (typeof OrderFlowerUsageScalarFieldEnum)[keyof typeof OrderFlowerUsageScalarFieldEnum]


export const StockEventScalarFieldEnum = {
  id: 'id',
  flowerId: 'flowerId',
  userId: 'userId',
  orderId: 'orderId',
  delta: 'delta',
  reason: 'reason',
  createdAt: 'createdAt'
} as const

export type StockEventScalarFieldEnum = (typeof StockEventScalarFieldEnum)[keyof typeof StockEventScalarFieldEnum]


export const OrderPhotoScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  uploaderId: 'uploaderId',
  fileName: 'fileName',
  filePath: 'filePath',
  mimeType: 'mimeType',
  sizeBytes: 'sizeBytes',
  createdAt: 'createdAt'
} as const

export type OrderPhotoScalarFieldEnum = (typeof OrderPhotoScalarFieldEnum)[keyof typeof OrderPhotoScalarFieldEnum]


export const OrderEventScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  userId: 'userId',
  type: 'type',
  from: 'from',
  to: 'to',
  message: 'message',
  createdAt: 'createdAt'
} as const

export type OrderEventScalarFieldEnum = (typeof OrderEventScalarFieldEnum)[keyof typeof OrderEventScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const UserOrderByRelevanceFieldEnum = {
  id: 'id',
  username: 'username',
  displayName: 'displayName',
  passwordHash: 'passwordHash'
} as const

export type UserOrderByRelevanceFieldEnum = (typeof UserOrderByRelevanceFieldEnum)[keyof typeof UserOrderByRelevanceFieldEnum]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const CustomerOrderByRelevanceFieldEnum = {
  id: 'id',
  fullName: 'fullName',
  phone: 'phone',
  email: 'email',
  address: 'address',
  notes: 'notes'
} as const

export type CustomerOrderByRelevanceFieldEnum = (typeof CustomerOrderByRelevanceFieldEnum)[keyof typeof CustomerOrderByRelevanceFieldEnum]


export const OrderOrderByRelevanceFieldEnum = {
  id: 'id',
  customerFullName: 'customerFullName',
  customerPhone: 'customerPhone',
  deliveryTime: 'deliveryTime',
  deliveryAddress: 'deliveryAddress',
  notes: 'notes',
  customerId: 'customerId',
  createdById: 'createdById',
  assignedToId: 'assignedToId',
  preparedById: 'preparedById',
  prepNotes: 'prepNotes'
} as const

export type OrderOrderByRelevanceFieldEnum = (typeof OrderOrderByRelevanceFieldEnum)[keyof typeof OrderOrderByRelevanceFieldEnum]


export const FlowerOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type FlowerOrderByRelevanceFieldEnum = (typeof FlowerOrderByRelevanceFieldEnum)[keyof typeof FlowerOrderByRelevanceFieldEnum]


export const OrderFlowerUsageOrderByRelevanceFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  flowerId: 'flowerId'
} as const

export type OrderFlowerUsageOrderByRelevanceFieldEnum = (typeof OrderFlowerUsageOrderByRelevanceFieldEnum)[keyof typeof OrderFlowerUsageOrderByRelevanceFieldEnum]


export const StockEventOrderByRelevanceFieldEnum = {
  id: 'id',
  flowerId: 'flowerId',
  userId: 'userId',
  orderId: 'orderId',
  reason: 'reason'
} as const

export type StockEventOrderByRelevanceFieldEnum = (typeof StockEventOrderByRelevanceFieldEnum)[keyof typeof StockEventOrderByRelevanceFieldEnum]


export const OrderPhotoOrderByRelevanceFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  uploaderId: 'uploaderId',
  fileName: 'fileName',
  filePath: 'filePath',
  mimeType: 'mimeType'
} as const

export type OrderPhotoOrderByRelevanceFieldEnum = (typeof OrderPhotoOrderByRelevanceFieldEnum)[keyof typeof OrderPhotoOrderByRelevanceFieldEnum]


export const OrderEventOrderByRelevanceFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  userId: 'userId',
  type: 'type',
  message: 'message'
} as const

export type OrderEventOrderByRelevanceFieldEnum = (typeof OrderEventOrderByRelevanceFieldEnum)[keyof typeof OrderEventOrderByRelevanceFieldEnum]

